import {createClient} from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-platform-session, content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const H=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const digits=(s:any)=>String(s||'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/\D/g,'');
const allowed=new Set(['image/jpeg','image/png','image/webp','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
const labels=(v:any)=>String(v||'').split(/[،,|;/]+/).map(x=>x.trim()).filter(Boolean);
const isStudentAffairsLabel=(v:any)=>{const x=String(v||'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');return ['student affairs','deputy students','وكيل شؤون الطلاب','وكيلة شؤون الطلاب','وكيل الشؤون الطلابية','وكيلة الشؤون الطلابية','شؤون الطلاب','الشؤون الطلابية'].includes(x)};

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
  if(req.method!=='POST')return J({error:'طريقة الطلب غير مدعومة'},405);
  const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  if(!url||!key)return J({error:'إعدادات الخدمة غير مكتملة'},500);
  const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),action=new URL(req.url).searchParams.get('action')||'';
  const body=async()=>await req.clone().json().catch(()=>({}));
  const session=async()=>{let raw=req.headers.get('x-platform-session')||'';if(!raw)throw Object.assign(Error('الجلسة مفقودة'),{status:401});let q=await sb.from('platform_sessions').select('*').eq('session_token_hash',await H(raw)).eq('status','active').gt('expires_at',new Date().toISOString()).maybeSingle();if(!q.data)throw Object.assign(Error('الجلسة غير صالحة'),{status:401});return q.data};
  const access=async(s:any)=>{if(!s?.school_id||!s?.user_id)return false;let q=await sb.from('school_members').select('role,role_label,status').eq('school_id',s.school_id).eq('user_id',s.user_id).maybeSingle();if(q.error)throw q.error;if(!q.data||String(q.data.status||'active').toLowerCase()!=='active')return false;let r=String(q.data.role||'').toLowerCase(),ok=labels(q.data.role_label).some(isStudentAffairsLabel);return (r==='agent'||r==='student_affairs')&&ok};
  const link=async(t:string)=>{let q=await sb.from('student_absence_excuse_links').select('*').eq('token_hash',await H(t)).maybeSingle(),x=q.data;if(!x||x.revoked_at||x.submitted_at||Date.parse(x.expires_at)<Date.now())return null;return x};
  try{
    if(action==='resolve'){let b=await body(),l=await link(String(b.token||''));if(!l)return J({error:'الرابط غير صالح أو منتهي'},404);return J({ok:true,student_name:l.student_name,stage:l.stage,grade:l.grade,class_name:l.class_name,absence_date:l.absence_date,absence_days:l.absence_days})}
    if(action==='verify'){let b=await body(),l=await link(String(b.token||''));if(!l)return J({error:'تعذر التحقق من البيانات'},404);if(l.locked_until&&Date.parse(l.locked_until)>Date.now())return J({error:'تعذر التحقق من البيانات. حاول لاحقًا.'},429);if(await H(digits(b.civil_id))!==l.civil_hash){let n=Number(l.verify_attempts||0)+1;await sb.from('student_absence_excuse_links').update({verify_attempts:n,locked_until:n>=5?new Date(Date.now()+15*60000).toISOString():null}).eq('id',l.id);return J({error:'تعذر التحقق من البيانات'},403)}let vt=crypto.randomUUID()+crypto.randomUUID();await sb.from('student_absence_excuse_links').update({verification_hash:await H(vt),verified_at:new Date().toISOString(),verify_attempts:0,locked_until:null}).eq('id',l.id);return J({ok:true,verification_token:vt})}
    if(action==='submit'){let f=await req.formData(),t=String(f.get('token')||''),v=String(f.get('verification_token')||''),note=String(f.get('note')||'').trim().slice(0,200),l=await link(t);if(!l||!l.verification_hash||await H(v)!==l.verification_hash)return J({error:'انتهى التحقق، أعد المحاولة'},403);if(!l.verified_at||Date.now()-Date.parse(l.verified_at)>30*60*1000)return J({error:'انتهت مهلة التحقق، أعد المحاولة'},403);let files=f.getAll('files').filter(x=>x instanceof File) as File[];if(!files.length||files.length>5)return J({error:'أرفق من 1 إلى 5 ملفات'},400);for(let x of files)if(x.size<=0||x.size>20*1024*1024||!allowed.has(x.type))return J({error:'أحد الملفات غير مسموح أو حجمه غير صالح'},415);let id=crypto.randomUUID(),ref='ABS-'+new Date().getFullYear()+'-'+crypto.randomUUID().slice(0,8).toUpperCase();let ins=await sb.from('student_absence_excuses').insert({id,school_id:l.school_id,link_id:l.id,reference_no:ref,student_source_id:l.student_source_id,student_name:l.student_name,stage:l.stage,grade:l.grade,class_name:l.class_name,track:l.track,absence_date:l.absence_date,absence_days:l.absence_days,parent_note:note,status:'pending',reviewer_user_id:l.reviewer_user_id}).select().single();if(ins.error)throw ins.error;for(let x of files){let ext=(x.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,''),fid=crypto.randomUUID(),path=`schools/${l.school_id}/users/${l.reviewer_user_id}/student_absence_excuses/${id}/${fid}.${ext}`;let up=await sb.storage.from('school-platform-files').upload(path,x,{contentType:x.type,upsert:false});if(up.error)throw up.error;let ai=await sb.from('student_absence_excuse_attachments').insert({excuse_id:id,school_id:l.school_id,storage_path:path,file_name:x.name,mime_type:x.type,size_bytes:x.size});if(ai.error)throw ai.error}await sb.from('student_absence_excuse_links').update({submitted_at:new Date().toISOString(),verification_hash:null}).eq('id',l.id);return J({ok:true,reference:ref})}

    let s=await session();
    if(!(await access(s)))return J({error:'هذا القسم متاح لوكيل/وكيلة شؤون الطلاب فقط'},403);
    if(action==='create-link'){let b=await body(),st=b.student||{},civil=digits(st.civil_id),days=Number(b.absence_days||1);if(!civil||!b.absence_date||!st.name)return J({error:'بيانات الطالب أو الغياب غير مكتملة'},400);if(days<1||days>60)return J({error:'عدد أيام الغياب غير صالح'},400);let token=crypto.randomUUID()+crypto.randomUUID(),exp=new Date(Date.now()+Math.min(30,Math.max(1,Number(b.expires_days||7)))*86400000).toISOString();let q=await sb.from('student_absence_excuse_links').insert({school_id:s.school_id,created_by:s.user_id,reviewer_user_id:s.user_id,token_hash:await H(token),student_source_id:String(st.source_id||''),student_name:String(st.name||''),civil_hash:await H(civil),stage:String(st.stage||''),grade:String(st.grade||''),class_name:String(st.class_name||''),track:String(st.track||''),absence_date:b.absence_date,absence_days:days,expires_at:exp}).select('id').single();if(q.error)throw q.error;return J({ok:true,id:q.data.id,token})}
    if(action==='list'){let b=await body();let q=sb.from('student_absence_excuses').select('*').eq('school_id',s.school_id).eq('reviewer_user_id',s.user_id).order('created_at',{ascending:false});if(b.status)q=q.eq('status',b.status);let r=await q;if(r.error)throw r.error;return J({ok:true,items:(r.data||[]).map((x:any)=>({...x,status_label:{pending:'بانتظار المراجعة',accepted:'مقبول',returned:'معاد للاستكمال',rejected:'مرفوض'}[x.status]||x.status}))})}
    if(action==='get'){let b=await body(),q=await sb.from('student_absence_excuses').select('*').eq('id',b.id).eq('school_id',s.school_id).eq('reviewer_user_id',s.user_id).maybeSingle();if(!q.data)return J({error:'الطلب غير موجود'},404);let a=await sb.from('student_absence_excuse_attachments').select('*').eq('excuse_id',q.data.id).eq('school_id',s.school_id),attachments=[];for(let x of a.data||[]){let u=await sb.storage.from('school-platform-files').createSignedUrl(x.storage_path,300);attachments.push({...x,url:u.data?.signedUrl||''})}return J({ok:true,item:{...q.data,attachments}})}
    if(action==='decide'){let b=await body();if(!b.previewed||!['accepted','returned','rejected'].includes(b.status))return J({error:'يجب معاينة المرفقات قبل اتخاذ القرار'},400);let q=await sb.from('student_absence_excuses').update({status:b.status,reviewer_note:String(b.note||'').slice(0,1000),reviewed_by:s.user_id,reviewed_at:new Date().toISOString()}).eq('id',b.id).eq('school_id',s.school_id).eq('reviewer_user_id',s.user_id).select().maybeSingle();if(!q.data)return J({error:'تعذر تحديث الطلب'},404);return J({ok:true})}
    return J({error:'عملية غير معروفة'},404)
  }catch(e:any){console.error(e);return J({error:e?.message||'خطأ داخلي'},e?.status||500)}
});
