




const STORAGE_KEY='externalEvaluationTreeSystem_v3_c3_c4_tree';
const ARCHIVE_KEY='externalEvaluationTreeSystem_visitArchive';
const VISIT_COUNTER_KEY='externalEvaluationTreeSystem_committedVisitCounter';
const weights={documents:15,surveys:10,classroom:20,environment:15,interviews:15,learningOutcomes:15,professional:10};
function currentHijriYear(){try{return new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{year:'numeric'}).format(new Date()).replace(/\D/g,'')||'1447'}catch(e){return '1447'}}
function nextArchiveNumber(){return Number(localStorage.getItem(VISIT_COUNTER_KEY)||0)+1}
function paddedVisit(n){return String(n||nextArchiveNumber()).padStart(3,'0')}
function visitCode(){return `EV-${currentHijriYear()}-${paddedVisit(state.visitNumber)}`}
function visitDisplay(){return state.archived?visitCode():'مسودة زيارة غير مؤرشفة'}
function emptySchool(){return {name:'',unit:'',system:'',moeId:'',shift:'',students:'',classes:'',gender:'',building:'',educationType:'',buildingIndependence:'',phone:'',email:'',address:'',general:'',admin:'',teaching:'',outcomes:'',environment:''}}
const state={locked:false,archived:false,visitNumber:nextArchiveNumber(),sourceStatus:'لم يتم جلب بيانات المدرسة بعد',school:emptySchool(),team:{leader:null,members:[]},scores:{documents:0,surveys:0,classroom:0,environment:0,interviewTeachers:0,interviewStudents:0,interviewCounselor:0,interviewAdmin:0,nafs:0,qodrat:0,tahsili:0,licenses:0,growth:0,trainingNeeds:0},surveyDetails:{students:{title:'استبانة المتعلمين',target:'المتعلمون',code:'',count:0,satisfaction:0,questions:['درجة رضاك عن بيئة المدرسة','وضوح شرح المعلم','توفر الدعم عند الحاجة'],notes:''},teachers:{title:'استبانة المعلمين',target:'المعلمون',code:'',count:0,satisfaction:0,questions:['وضوح قيادة المدرسة للمؤشرات','توفر الدعم المهني','فاعلية التواصل الداخلي'],notes:''},families:{title:'استبانة الأسرة',target:'أولياء الأمور',code:'',count:0,satisfaction:0,questions:['رضاك عن تواصل المدرسة','وضوح متابعة التحصيل','مستوى الأمان والانضباط'],notes:''}},notes:{},sectionNotes:{},criteria:{},signature:null};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function sectionHeader(title,icon='panel-top'){return `<div class="sectionTitle"><h2><i data-lucide="${icon}"></i> ${title}</h2><span class="pill">${visitDisplay()}</span></div>`}
function toolScore(id){return Number(state.scores[id]||0)}
function interviewAvg(){return Math.round((toolScore('interviewTeachers')+toolScore('interviewStudents')+toolScore('interviewCounselor')+toolScore('interviewAdmin'))/4)}
function learningAvg(){let arr=[toolScore('nafs')]; if(String(state.school.unit).includes('ثانوية')) arr.push(toolScore('qodrat'),toolScore('tahsili')); return Math.round(arr.reduce((a,b)=>a+b,0)/arr.length)}
function professionalAvg(){return Math.round((toolScore('licenses')+toolScore('growth')+toolScore('trainingNeeds'))/3)}
function finalScore(){return Math.round(toolScore('documents')*.15+toolScore('surveys')*.10+toolScore('classroom')*.20+toolScore('environment')*.15+interviewAvg()*.15+learningAvg()*.15+professionalAvg()*.10)}
function decisionText(score=finalScore()){if(score>=90)return ['معتمد متميز','excellent']; if(score>=80)return ['معتمد','good']; if(score>=70)return ['معتمد بشروط','conditional']; return ['غير معتمد','fail']}
function labelOf(k){return {documents:'تحليل الوثائق',surveys:'الاستبانات',classroom:'الملاحظة الصفية',environment:'البيئة التعليمية',interviews:'المقابلات',learningOutcomes:'نواتج التعلم',professional:'الأداء المهني'}[k]||k}
function sourceCandidates(){return ['selfEvaluationSchoolData','schoolSelfEvaluationData','selfEvaluationData','schoolEvaluationBasicData','schoolBasicData','principalSchoolData','schoolProfile','smartSchoolData']}
function normalizeSchoolData(o){if(!o) return null; let root=o.school||o.schoolData||o.basic||o.data||o; return {name:root.name||root.schoolName||root['اسم المدرسة']||'',unit:root.unit||root.stage||root.phase||root['المرحلة']||root['الوحدة (المرحلة)']||'',system:root.system||root.schoolSystem||root['نظام المدرسة']||'',moeId:root.moeId||root.ministryNumber||root.schoolNo||root['الرقم الوزاري']||'',shift:root.shift||root.studyTime||root['وقت الدراسة']||'',students:root.students||root.studentCount||root['عدد الطلاب/الطالبات']||'',classes:root.classes||root.classCount||root['عدد الفصول']||'',gender:root.gender||root.schoolGender||root['جنس المدرسة']||'',building:root.building||root.buildingType||root['نوع المبنى']||'',educationType:root.educationType||root['نوع التعليم']||'',buildingIndependence:root.buildingIndependence||root['استقلالية المبنى']||'',phone:root.phone||root.schoolPhone||root['هاتف المدرسة']||'',email:root.email||root.schoolEmail||root['بريد المدرسة']||'',address:root.address||root['العنوان']||'',general:root.general||root.generalPerformance||root['مستوى الأداء العام']||'',admin:root.admin||root.adminLevel||root['مستوى الإدارة المدرسية']||'',teaching:root.teaching||root.teachingLevel||root['مستوى التعليم والتعلم']||'',outcomes:root.outcomes||root.learningOutcomes||root['مستوى نواتج التعلم']||'',environment:root.environment||root.environmentLevel||root['مستوى البيئة المدرسية']||''}}
function importSchoolFromSelfEvaluation(){let found=null,key=''; for(const k of sourceCandidates()){try{let raw=localStorage.getItem(k); if(!raw) continue; let obj=JSON.parse(raw); let norm=normalizeSchoolData(obj); if(norm && Object.values(norm).some(Boolean)){found=norm; key=k; break}}catch(e){}} if(!found){state.sourceStatus='لم يتم العثور على بيانات محفوظة من سجلات متابعة التقويم الذاتي؛ يمكنك تعبئة الجدول يدويًا الآن.'; updateAll(); alert(state.sourceStatus); return} state.school={...state.school,...found}; state.sourceStatus='تم جلب بيانات المدرسة من سجلات متابعة التقويم الذاتي ('+key+')'; updateAll()}
function setSchoolFromInputs(){$$('[data-school]').forEach(el=>state.school[el.dataset.school]=el.value);updateSecondaryVisibility();updateAll()}
function selectOptions(options,val,blank='اختر'){return `<option value="">${blank}</option>`+options.map(o=>`<option ${String(val)==o?'selected':''}>${o}</option>`).join('')}
function updateSecondaryVisibility(){let show=String(state.school.unit).includes('ثانوية');$$('.secondaryOnly').forEach(el=>el.style.display=show?'flex':'none')}
function schoolDataHTML(){return sectionHeader('بيانات المدرسة التفاعلية','school')+`<div class="sourceBar"><div><b>مصدر البيانات الأساسية:</b> <span class="hint">${state.sourceStatus}</span><br><span class="small">لا تُعبأ بيانات افتراضية داخل البطاقة؛ يتم جلبها من النموذج المتطابق في سجلات متابعة التقويم الذاتي أو تعبئتها يدويًا.</span></div><button class="btn primary" onclick="importSchoolFromSelfEvaluation()"><i data-lucide="download-cloud"></i>جلب من سجلات متابعة التقويم الذاتي</button></div><div class="tableWrap"><table><tr><th>اسم المدرسة</th><th>الوحدة (المرحلة)</th><th>نظام المدرسة</th><th>الرقم الوزاري</th><th>وقت الدراسة</th></tr><tr><td><input data-school="name" placeholder="اسم المدرسة" value="${state.school.name}"></td><td><select data-school="unit">${selectOptions(['المرحلة الابتدائية','المرحلة المتوسطة','المرحلة الثانوية'],state.school.unit,'اختر المرحلة')}</select></td><td><input data-school="system" placeholder="عام / تحفيظ..." value="${state.school.system}"></td><td><input data-school="moeId" placeholder="الرقم الوزاري" value="${state.school.moeId}"></td><td><select data-school="shift">${selectOptions(['صباحي','مسائي'],state.school.shift,'اختر')}</select></td></tr><tr><th>عدد الطلاب/الطالبات</th><th>عدد الفصول</th><th>جنس المدرسة</th><th>نوع المبنى</th><th>نوع التعليم</th></tr><tr><td><input data-school="students" placeholder="0" value="${state.school.students}"></td><td><input data-school="classes" placeholder="0" value="${state.school.classes}"></td><td><select data-school="gender">${selectOptions(['بنين','بنات','مشترك'],state.school.gender,'اختر')}</select></td><td><select data-school="building">${selectOptions(['حكومي','مستأجر'],state.school.building,'اختر')}</select></td><td><select data-school="educationType">${selectOptions(['تعليم عام','تحفيظ','أهلي'],state.school.educationType,'اختر')}</select></td></tr><tr><th>استقلالية المبنى</th><th>هاتف المدرسة</th><th>بريد المدرسة</th><th colspan="2">العنوان</th></tr><tr><td><select data-school="buildingIndependence">${selectOptions(['مستقل','مشترك'],state.school.buildingIndependence,'اختر')}</select></td><td><input data-school="phone" placeholder="هاتف المدرسة" value="${state.school.phone}"></td><td><input data-school="email" placeholder="بريد المدرسة" value="${state.school.email}"></td><td colspan="2"><input data-school="address" placeholder="العنوان" value="${state.school.address}"></td></tr><tr><th>مستوى الأداء العام</th><th>مستوى الإدارة المدرسية</th><th>مستوى التعليم والتعلم</th><th>مستوى نواتج التعلم</th><th>مستوى البيئة المدرسية</th></tr><tr>${['general','admin','teaching','outcomes','environment'].map(k=>`<td><select data-school="${k}">${selectOptions(['تميز','تقدم','انطلاق','تهيئة'],state.school[k],'اختر')}</select></td>`).join('')}</tr></table></div>`}
function teamHTML(){return sectionHeader('بيانات الفريق','users')+`<div class="grid2"><div class="formCard"><h3>رئيس الفريق</h3><div class="grid2"><select id="leaderTitle"><option>أ.</option><option>د.</option></select><input id="leaderName" placeholder="اسم رئيس الفريق"></div><button class="btn primary" onclick="addLeader()" style="margin-top:10px"><i data-lucide="plus"></i>إضافة رئيس فريق</button></div><div class="formCard"><h3>أعضاء الفريق</h3><div class="grid"><select id="memberTitle"><option>أ.</option><option>د.</option></select><input id="memberName" placeholder="اسم العضو"><input id="memberRole" placeholder="المسمى / الدور"></div><button class="btn primary" onclick="addMember()" style="margin-top:10px"><i data-lucide="plus"></i>إضافة عضو</button></div></div><div class="tableWrap"><table><thead><tr><th>م</th><th>اللقب</th><th>الاسم</th><th>المسمى الوظيفي</th><th>الإجراء</th></tr></thead><tbody id="membersRows"></tbody></table></div>`}
function renderMembers(){let rows=state.team.members.map((m,i)=>`<tr><td>${i+1}</td><td>${m.title}</td><td>${m.name}</td><td>${m.role}</td><td><button class="btn light" onclick="removeMember(${i})">حذف</button></td></tr>`).join(''); if($('#membersRows')) $('#membersRows').innerHTML=rows||'<tr><td colspan="5">لم يتم إضافة أعضاء بعد</td></tr>'}
function addLeader(){state.team.leader={title:$('#leaderTitle').value,name:$('#leaderName').value||'رئيس الفريق'};updateAll()}
function addMember(){let name=$('#memberName').value.trim(); if(!name)return alert('أدخل اسم العضو'); state.team.members.push({title:$('#memberTitle').value,name,role:$('#memberRole').value||'عضو فريق التقويم'});updateAll()}
function removeMember(i){state.team.members.splice(i,1);updateAll()}
const defaultRubricItems={documents:['توفر الوثائق والخطط الرسمية','ارتباط الوثائق بمؤشرات الأداء','تحديث السجلات وانتظامها','وضوح الأدلة الداعمة داخل الوثائق'],classroom:['التخطيط للتدريس','استراتيجيات التدريس','التفاعل وإدارة الصف','التقويم والتغذية الراجعة'],environment:['السلامة ومخارج الطوارئ','النظافة والتهوية والإضاءة','المعامل ومصادر التعلم','تهيئة البيئة التعليمية الداعمة'],interviewTeachers:['وضوح أدوار المعلمين','الممارسات التدريسية','النمو المهني','دعم التعثر'],interviewStudents:['الأمان المدرسي','جاذبية التعلم','الدعم الأكاديمي','المشاركة الطلابية'],interviewCounselor:['متابعة التعثر','خطط التوجيه والإرشاد','معالجة السلوك','التواصل مع الأسرة'],interviewAdmin:['قيادة التخطيط','متابعة المؤشرات','حوكمة العمل المدرسي','الشراكة والتحسين'],nafs:['تحليل نتائج نافس','المقارنة بالمتوسطات','خطط معالجة الفجوات','تحسن النتائج'],qodrat:['متوسط القدرات','نسبة التحسن','البرامج الداعمة','المقارنة السنوية'],tahsili:['متوسط التحصيلي','نسبة التحسن','تحليل مواد الضعف','الخطط العلاجية'],licenses:['نسبة المجتازين','استثمار نتائج الرخص','خطط دعم غير المجتازين','جاهزية الكادر'],growth:['ساعات النمو المهني','ارتباط النمو بالاحتياج','أثر التدريب','تنوع البرامج'],trainingNeeds:['تحديد الاحتياجات','خطة تدريبية واضحة','أولوية الاحتياجات','متابعة الأثر']};
const flexibleRubricIds=['documents','classroom','environment','interviewTeachers','interviewStudents','interviewCounselor','interviewAdmin','nafs','qodrat','tahsili','licenses','growth','trainingNeeds'];
function getCriteria(id){state.criteria=state.criteria||{}; if(!state.criteria[id]) state.criteria[id]=[...(defaultRubricItems[id]||[])]; return state.criteria[id]}
function recalcRubricScore(id){let criteria=getCriteria(id), notes=state.notes[id]||{}, vals=criteria.map((_,i)=>Number(notes[i]?.score||0)); state.scores[id]=criteria.length?Math.round(vals.reduce((a,b)=>a+b,0)/criteria.length*20):0}
function sectionNoteTitle(id){if(id.startsWith('interview')) return 'مرئيات ما بعد المقابلة'; if(id==='documents') return 'مرئيات تحليل الوثائق'; if(['licenses','growth','trainingNeeds'].includes(id)) return 'مرئيات الأداء المهني'; if(['nafs','qodrat','tahsili'].includes(id)) return 'مرئيات نواتج التعلم'; return 'مرئيات فريق التقويم'}
function rubricHTML(id,title){let score=state.scores[id]||0, criteria=getCriteria(id), flexible=flexibleRubricIds.includes(id); return sectionHeader(title,'list-check')+`<div class="formCard"><div class="grid2"><div><span class="pill">الدرجة الحالية: ${score}%</span><div class="progress" style="margin-top:10px"><div class="bar" style="width:${score}%"></div></div></div><div class="quickScore"><span class="small">تعبئة سريعة:</span>${[1,2,3,4,5].map(v=>`<button class="scoreBtn" onclick="autoScore('${id}',${v})">${v}</button>`).join('')}</div></div>${flexible?`<div class="criterionTools"><button class="addCriterionBtn" onclick="addCriterion('${id}')"><i data-lucide="plus"></i> إضافة معيار</button><span class="small">يمكن لفريق التقويم تعديل المعايير أو حذفها حسب طبيعة الزيارة.</span></div>`:''}<div class="score5 ${flexible?'dynamicCriteria':''}"><div class="head">المعيار</div><div class="head">1</div><div class="head">2</div><div class="head">3</div><div class="head">4</div><div class="head">5</div>${flexible?'<div class="head">إجراء</div>':''}${criteria.length?criteria.map((item,idx)=>`<div>${flexible?`<input class="criterionInput" value="${escapeHtml(item)}" onchange="setCriterion('${id}',${idx},this.value)" placeholder="اكتب المعيار">`:item}</div>${[1,2,3,4,5].map(v=>`<div><button class="scoreBtn ${(state.notes[id]?.[idx]?.score==v)?'active':''}" onclick="setRubric('${id}',${idx},${v})">${v}</button></div>`).join('')}${flexible?`<div><button class="iconBtn" onclick="removeCriterion('${id}',${idx})">حذف</button></div>`:''}`).join(''):`<div class="rubricFooter">لا توجد معايير. اضغط إضافة معيار للبدء.</div>`}<div class="rubricFooter"><h3>${sectionNoteTitle(id)}</h3><textarea class="noteArea" placeholder="اكتب مرئيات فريق التقويم التي تسند بطاقة التقييم أعلاه..." onchange="setSectionNote('${id}',this.value)">${state.sectionNotes[id]||''}</textarea></div></div></div>`}
function escapeHtml(str=''){return String(str).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setRubric(id,idx,score){state.notes[id]=state.notes[id]||{}; state.notes[id][idx]=state.notes[id][idx]||{}; state.notes[id][idx].score=score; recalcRubricScore(id); updateAll()}
function setSectionNote(id,val){state.sectionNotes[id]=val; save()}
function autoScore(id,score){getCriteria(id).forEach((_,i)=>{state.notes[id]=state.notes[id]||{}; state.notes[id][i]={score}}); recalcRubricScore(id); updateAll()}
function setCriterion(id,idx,val){let criteria=getCriteria(id); criteria[idx]=String(val||'').trim()||'معيار جديد'; save(); updateAll()}
function addCriterion(id){let criteria=getCriteria(id); criteria.push('معيار جديد'); state.notes[id]=state.notes[id]||{}; state.notes[id][criteria.length-1]={score:0}; recalcRubricScore(id); updateAll()}
function removeCriterion(id,idx){let criteria=getCriteria(id); if(criteria.length<=1){alert('يجب إبقاء معيار واحد على الأقل.'); return} criteria.splice(idx,1); let old=state.notes[id]||{}, shifted={}; criteria.forEach((_,i)=>{shifted[i]=old[i>=idx?i+1:i]||{score:0}}); state.notes[id]=shifted; recalcRubricScore(id); updateAll()}
function surveyLabel(k){return {students:'استبانة المتعلمين',teachers:'استبانة المعلمين',families:'استبانة الأسرة'}[k]||k}
function ensureSurvey(g){state.surveyDetails[g]=state.surveyDetails[g]||{title:surveyLabel(g),target:g,code:'',count:0,satisfaction:0,questions:[],notes:''}; state.surveyDetails[g].questions=state.surveyDetails[g].questions||[]; return state.surveyDetails[g]}
function generateSurveyCode(group){let d=ensureSurvey(group); d.code='EV-'+group.toUpperCase()+'-'+String(state.visitNumber).padStart(3,'0')+'-'+Date.now().toString().slice(-4); updateAll()}
function addSurveyQuestion(group){let inp=$(`#q_${group}`); let val=(inp?.value||'').trim(); if(!val)return alert('أدخل نص السؤال'); ensureSurvey(group).questions.push(val); inp.value=''; recalcSurveys(); updateAll()}
function removeSurveyQuestion(group,idx){ensureSurvey(group).questions.splice(idx,1); updateAll()}
function updateSurveyField(group,field,value){let d=ensureSurvey(group); d[field]=['count','satisfaction'].includes(field)?Number(value||0):value; recalcSurveys(); updateAll()}
function recalcSurveys(){let groups=['students','teachers','families']; let vals=groups.map(g=>Number(ensureSurvey(g).satisfaction||0)).filter(v=>v>0); state.scores.surveys=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0; save()}
function surveysHTML(){let groups=['students','teachers','families'];let score=toolScore('surveys');return sectionHeader('الاستبانات الداخلية','clipboard-list')+`<div class="c4Notice">تم تحويل الاستبانات إلى استبانات داخلية بسيطة داخل النموذج: يختار الفريق الأسئلة، يولد كودًا داخليًا، ويسجل عدد المشاركين ونسبة الرضا لتغذية التحليل الذكي دون الانتقال إلى نماذج خارجية.</div><div class="formCard"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><h3>ملخص الاستبانات</h3><p class="small">يتم احتساب متوسط رضا المتعلمين والمعلمين والأسرة تلقائيًا.</p></div><span class="pill">متوسط الاستبانات: ${score}%</span></div><div class="progress"><div class="bar" style="width:${score}%"></div></div></div><div class="surveyGrid">${groups.map(g=>{let d=ensureSurvey(g);return `<div class="surveyCard"><h3>${surveyLabel(g)}</h3><div class="mini">عنوان الاستبانة</div><input value="${d.title||''}" onchange="updateSurveyField('${g}','title',this.value)" placeholder="عنوان الاستبانة"><div class="mini">الفئة المستهدفة</div><input value="${d.target||''}" onchange="updateSurveyField('${g}','target',this.value)" placeholder="الطلاب / المعلمون / الأسرة"><div class="mini">إضافة سؤال</div><div style="display:grid;grid-template-columns:1fr auto;gap:8px"><input id="q_${g}" placeholder="اكتب سؤالًا مختصرًا"><button class="btn primary" onclick="addSurveyQuestion('${g}')"><i data-lucide="plus"></i></button></div><div class="questionList">${(d.questions||[]).map((q,i)=>`<div class="questionRow"><span>${q}</span><button class="btn light" onclick="removeSurveyQuestion('${g}',${i})">×</button></div>`).join('')||'<div class="questionRow"><span class="small">لم يتم إضافة أسئلة بعد</span><span></span></div>'}</div><button class="btn gold" onclick="generateSurveyCode('${g}')"><i data-lucide="qr-code"></i>توليد كود الاستبانة</button><div class="qrBox">${d.code?`<div>كود الاستبانة<br><span class="internalCode">${d.code}</span><br><span class="small">يستخدم داخل النموذج أو عند الربط لاحقًا بـ Supabase</span></div>`:'اضغط توليد كود الاستبانة'}</div><div class="grid2"><div><div class="mini">عدد المشاركين</div><input type="number" min="0" value="${d.count||''}" onchange="updateSurveyField('${g}','count',this.value)" placeholder="0"></div><div><div class="mini">نسبة الرضا</div><input type="number" min="0" max="100" value="${d.satisfaction||''}" onchange="updateSurveyField('${g}','satisfaction',this.value)" placeholder="0 - 100"></div></div><div class="mini">تحليل مختصر للنتائج</div><textarea rows="3" onchange="updateSurveyField('${g}','notes',this.value)" placeholder="أبرز نتائج هذه الاستبانة...">${d.notes||''}</textarea></div>`}).join('')}</div>`}
function metricRows(){return [['documents',toolScore('documents')],['surveys',toolScore('surveys')],['classroom',toolScore('classroom')],['environment',toolScore('environment')],['interviews',interviewAvg()],['learningOutcomes',learningAvg()],['professional',professionalAvg()]]}
function indicatorsHTML(){let rows=metricRows(),fs=finalScore();return sectionHeader('مؤشرات الأداء','gauge')+`<div class="analysisCards"><div class="analysisCard"><span>المؤشر العام</span><br><b>${fs}%</b></div><div class="analysisCard"><span>نسبة الإنجاز</span><br><b>${completion()}%</b></div><div class="analysisCard"><span>عدد المرئيات</span><br><b>${evidenceCount()}</b></div><div class="analysisCard"><span>قرار الاعتماد</span><br><b style="font-size:1.1rem">${decisionText(fs)[0]}</b></div></div><table class="analysisTable"><thead><tr><th>المجال</th><th>الوزن</th><th>النتيجة</th><th>المساهمة في الدرجة</th></tr></thead><tbody>${rows.map(([k,v])=>`<tr><td>${labelOf(k)}</td><td>${weights[k]||''}%</td><td>${v}%</td><td>${Math.round(v*(weights[k]||0)/100)} نقطة</td></tr>`).join('')}</tbody></table>`}
function gapsHTML(){let gaps=metricRows().filter(([_,v])=>v>0&&v<70).sort((a,b)=>a[1]-b[1]);return sectionHeader('فجوات الأداء','triangle-alert')+`<div class="c4Notice">تعرض هذه الشاشة المجالات الأقل من 70% فقط.</div>${gaps.length?`<table class="analysisTable"><thead><tr><th>المجال</th><th>النتيجة</th><th>الفجوة عن الحد الأدنى</th><th>إجراء مقترح</th></tr></thead><tbody>${gaps.map(([k,v])=>`<tr><td>${labelOf(k)}</td><td>${v}%</td><td>${70-v} نقطة</td><td>إدراج ${labelOf(k)} ضمن خطة تحسين عاجلة.</td></tr>`).join('')}</tbody></table>`:`<div class="formCard"><p>لا توجد فجوات أداء حرجة حتى الآن وفق البيانات المدخلة.</p></div>`}`}
function strengthsHTML(){let strengths=metricRows().filter(([_,v])=>v>=85).sort((a,b)=>b[1]-a[1]);return sectionHeader('نقاط القوة','badge-check')+`<div class="c4Notice">تعرض هذه الشاشة المجالات التي تحقق 85% فأكثر فقط.</div>${strengths.length?`<table class="analysisTable"><thead><tr><th>المجال</th><th>النتيجة</th><th>صياغة نقطة القوة</th></tr></thead><tbody>${strengths.map(([k,v])=>`<tr><td>${labelOf(k)}</td><td>${v}%</td><td>تميز واضح في ${labelOf(k)} مدعوم بنتائج وأدلة الزيارة.</td></tr>`).join('')}</tbody></table>`:`<div class="formCard"><p>لم تظهر نقاط قوة وفق حد 85% حتى الآن. ستظهر تلقائيًا بعد إدخال الدرجات.</p></div>`}`}
function prioritiesHTML(){let rows=metricRows().filter(([_,v])=>v>0).sort((a,b)=>a[1]-b[1]).slice(0,4);return sectionHeader('الأولويات التحسينية','list-todo')+`${rows.length?`<div class="formCard"><ol>${rows.map(([k,v])=>`<li><b>${labelOf(k)}</b> — ${v}%: أولوية تحسين مرتبطة بنتائج التقويم.</li>`).join('')}</ol></div>`:`<div class="formCard"><p>ستظهر الأولويات تلقائيًا بعد إدخال درجات أدوات التقييم.</p></div>`}`}
function scoreRows(){let rows=metricRows(); return rows.map(([k,v])=>`<div style="margin:10px 0"><div style="display:flex;justify-content:space-between"><b>${labelOf(k)}</b><span>${v}%</span></div><div class="progress"><div class="bar" style="width:${v}%"></div></div></div>`)}
function completion(){let keys=['documents','surveys','classroom','environment','interviewTeachers','interviewStudents','interviewCounselor','interviewAdmin','nafs','licenses','growth','trainingNeeds']; if(String(state.school.unit).includes('ثانوية')) keys.push('qodrat','tahsili'); return Math.round(keys.filter(k=>toolScore(k)>0).length/keys.length*100)}
function evidenceCount(){return Object.values(state.sectionNotes||{}).filter(Boolean).length}
function dashboardHTML(){let fs=finalScore(),dec=decisionText(fs);return sectionHeader('Dashboard الزيارة','layout-dashboard')+`<div class="cards"><div class="stat"><span>حالة الزيارة</span><b style="font-size:1.15rem">${visitDisplay()}</b><span>${state.archived?'رقم مؤرشف ومثبت':'لا يتم تثبيت الرقم إلا بعد الأرشفة'}</span></div><div class="stat"><span>نسبة الإنجاز</span><b>${completion()}%</b><div class="progress"><div class="bar" style="width:${completion()}%"></div></div></div><div class="stat"><span>متوسط التقييم</span><b>${fs}%</b><div class="progress"><div class="bar" style="width:${fs}%"></div></div></div><div class="stat"><span>قرار الاعتماد</span><b style="font-size:1.2rem">${dec[0]}</b><span>محسوب تلقائيًا</span></div></div><div class="grid2"><div class="formCard"><h3>الأوزان المعتمدة</h3>${Object.entries(weights).map(([k,w])=>`<div style="display:flex;justify-content:space-between;margin:8px 0"><span>${labelOf(k)}</span><b>${w}%</b></div>`).join('')}</div><div class="formCard"><h3>ملخص المجالات</h3>${scoreRows().join('')}</div></div>`}
function approvalHTML(){let leader=state.team.leader?`${state.team.leader.title} ${state.team.leader.name}`:'لم يتم تحديد رئيس الفريق';return sectionHeader('اعتماد فريق التقويم الزائر','signature')+`<div class="grid2"><div class="formCard"><h3>يعتمد من أعضاء فريق التقويم الزائر</h3><p>${state.team.members.length?state.team.members.map(m=>m.title+' '+m.name).join('، '):'لم يتم إضافة أعضاء بعد'}</p><hr><p><b>رئيس الفريق:</b> <span class="success">${leader}</span></p></div><div class="formCard"><h3>التوقيع الرقمي لرئيس الفريق</h3><div id="signatureBox" class="signatureBox ${state.signature?'':'empty'}" onclick="$('#signatureInput').click()">${state.signature?`<img src="${state.signature}" alt="توقيع رئيس الفريق">`:''}</div><button class="btn primary" onclick="$('#signatureInput').click()">رفع صورة التوقيع</button><button class="btn light" onclick="clearSignature()" style="margin-inline-start:8px">مسح</button><div class="small">PNG / JPG / SVG - لا يتمدد التوقيع ويحتوى داخل الإطار.</div></div></div>`}
function generateReportText(){let fs=finalScore(),dec=decisionText(fs)[0],strengths=[],gaps=[]; for(const [k,v] of [['تحليل الوثائق',toolScore('documents')],['الاستبانات',toolScore('surveys')],['الملاحظة الصفية',toolScore('classroom')],['البيئة التعليمية',toolScore('environment')],['المقابلات',interviewAvg()],['نواتج التعلم',learningAvg()],['الأداء المهني',professionalAvg()]]){if(v>=85)strengths.push(k); if(v>0&&v<70)gaps.push(k)} return `<h3>ملخص التقرير</h3><p>بلغت النتيجة النهائية للمدرسة <b>${fs}%</b>، وبناءً على محرك الأوزان يكون قرار الاعتماد المقترح: <b>${dec}</b>.</p><h3>نقاط القوة</h3><ul>${(strengths.length?strengths:['لم تظهر نقاط قوة مكتملة بعد']).map(x=>`<li>${x}</li>`).join('')}</ul><h3>فجوات الأداء</h3><ul>${(gaps.length?gaps:['لا توجد فجوات حرجة وفق البيانات المدخلة']).map(x=>`<li>${x}</li>`).join('')}</ul><h3>التوصيات</h3><p>يوصى ببناء خطة تحسين مركزة على المجالات الأقل من 70%، وربط كل إجراء بمرئية قابلة للتحقق ومؤشر قياس زمني.</p>`}
function smartReportHTML(){return sectionHeader('التقرير الذكي','file-text')+`<div class="reportBox" id="reportBox">${generateReportText()}</div><button class="btn primary" onclick="$('#reportBox').innerHTML=generateReportText()">تحديث التقرير</button>`}
function decisionHTML(){let fs=finalScore(),dec=decisionText(fs);return sectionHeader('قرار الاعتماد','award')+`<div class="decision ${dec[1]}">${dec[0]} — ${fs}%</div><div class="formCard" style="margin-top:14px"><h3>قواعد القرار</h3><p>90 فأكثر: معتمد متميز، 80–89: معتمد، 70–79: معتمد بشروط، أقل من 70: غير معتمد.</p></div>`}
function finalLockHTML(){return sectionHeader('اعتماد نهائي','lock')+`<div class="formCard"><p>عند الاعتماد النهائي يتم قفل التعديل في النموذج وحفظ النسخة كزيارة مكتملة برقم أرشيفي مستقل لا يثبت إلا عند التصدير للأرشيف.</p><button class="btn dark" onclick="lockVisit()"><i data-lucide="lock"></i>اعتماد نهائي وقفل الزيارة</button><span class="pill" style="margin-right:8px">الحالة: ${state.locked?'مقفلة':'قيد التنفيذ'}</span></div>`}
function simpleSection(title,msg,icon='circle'){return sectionHeader(title,icon)+`<div class="formCard"><p>${msg}</p>${scoreRows().join('')}</div>`}
function archiveHTML(){let archive=JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]');return sectionHeader('الأرشيف والشواهد','archive')+`<div class="formCard"><p>سيتم تصدير الزيارة إلى: قسم المدير ← مكتبة القسم ← زيارة فريق التقويم الخارجي، باسم يحمل رقم الزيارة لمنع الحذف أو الاستبدال عند الأرشفة التالية.</p><button class="btn gold" onclick="exportToLibrary()">تصدير الآن</button><span class="visitBadge">${visitDisplay()}</span></div><div class="archiveList">${archive.map(a=>`<div class="archiveItem"><b>${a.name}</b><span>${a.date}</span></div>`).join('')||'<div class="archiveItem"><span>لا توجد زيارات مؤرشفة بعد</span></div>'}</div>`}
function updateAll(){ $('#dashboard').innerHTML=dashboardHTML(); $('#schoolData').innerHTML=schoolDataHTML(); $('#teamData').innerHTML=teamHTML(); $('#approval').innerHTML=approvalHTML(); for(const [id,title] of Object.entries({documents:'تحليل الوثائق',classroom:'الملاحظة الصفية',environment:'ملاحظة البيئة التعليمية',interviewTeachers:'مقابلة المعلمين',interviewStudents:'مقابلة المتعلمين',interviewCounselor:'مقابلة الموجه الطلابي',interviewAdmin:'مقابلة الإدارة المدرسية',nafs:'نتائج نافس',qodrat:'اختبارات القدرات',tahsili:'الاختبار التحصيلي',licenses:'الرخص المهنية',growth:'النمو المهني',trainingNeeds:'الاحتياج التدريبي'})) $('#'+id).innerHTML=rubricHTML(id,title); $('#surveys').innerHTML=surveysHTML(); $('#learningCompare').innerHTML=simpleSection('التحليل المقارن','يعرض هذا القسم مقارنة نواتج التعلم بين المدرسة والمتوسطات المرجعية حسب البيانات المدخلة.','chart-no-axes-combined'); $('#indicators').innerHTML=indicatorsHTML(); $('#gaps').innerHTML=gapsHTML(); $('#strengths').innerHTML=strengthsHTML(); $('#priorities').innerHTML=prioritiesHTML(); $('#smartReport').innerHTML=smartReportHTML(); $('#decision').innerHTML=decisionHTML(); $('#finalLock').innerHTML=finalLockHTML(); $('#archive').innerHTML=archiveHTML(); renderMembers(); bindInputs(); updateSecondaryVisibility(); save(); lucide.createIcons() }
function bindInputs(){$$('[data-school]').forEach(el=>el.onchange=setSchoolFromInputs)}
function switchSection(id){if(state.locked&&!['dashboard','smartReport','decision','archive','finalLock'].includes(id))return alert('الزيارة مقفلة بعد الاعتماد النهائي'); $$('.section').forEach(s=>s.classList.remove('active')); $('#'+id)?.classList.add('active'); $$('.treeItem,.treeToggle').forEach(b=>b.classList.remove('active')); $$(`[data-target="${id}"]`).forEach(b=>b.classList.add('active'))}

function getVisitParams(){const q=new URLSearchParams(location.search);return{school_id:q.get('school_id')||q.get('schoolId')||localStorage.getItem('active_school_id')||localStorage.getItem('current_school_id')||localStorage.getItem('school_id')||'',visit_token:q.get('visit_token')||q.get('visitToken')||'',visit_number:q.get('visit_number')||q.get('visitNumber')||visitCode()}}
function getCurrentUserId(){try{let u=JSON.parse(localStorage.getItem('currentSchoolUser')||localStorage.getItem('currentUser')||'{}');return u.id||u.user_id||null}catch(e){return null}}
function buildSmartCardSupabasePayload(){let params=getVisitParams();return{school_id:params.school_id,created_by:getCurrentUserId(),draft_number:params.visit_number,visit_number:params.visit_number,visit_year:String(new Date().getFullYear()),status:state.archived?'archived':'draft',form_data:{smartCard:state,visit_token:params.visit_token,visit_number:params.visit_number,school_id:params.school_id,savedAt:new Date().toISOString()},final_score:finalScore(),accreditation_decision:decisionText(finalScore())[0],team_leader_name:state.teamLeaderName||state.leaderName||''}}
async function saveSmartCardDraftRemote(showToast=false){try{if(!window.SmartSchoolSupabase||!SmartSchoolSupabase.saveExternalEvaluationDraft)return null;let row=await SmartSchoolSupabase.saveExternalEvaluationDraft(buildSmartCardSupabasePayload());if(row&&row.id){state.supabaseDraftId=row.id;save()}if(showToast)alert('تم حفظ مسودة البطاقة في Supabase.');return row}catch(e){console.warn('تعذر حفظ مسودة البطاقة في Supabase:',e);if(showToast)alert('تم الحفظ محليًا، وتعذر حفظ Supabase: '+(e.message||e));return null}}
async function saveSmartCardVisitRemote(showToast=false){try{if(!window.SmartSchoolSupabase||!SmartSchoolSupabase.saveExternalEvaluationVisit)return null;let payload=buildSmartCardSupabasePayload();payload.id=state.supabaseVisitId||null;let row=await SmartSchoolSupabase.saveExternalEvaluationVisit(payload);if(row&&row.id){state.supabaseVisitId=row.id;save()}if(showToast)alert('تم حفظ الزيارة المؤرشفة في Supabase.');return row}catch(e){console.warn('تعذر حفظ الزيارة في Supabase:',e);if(showToast)alert('تمت الأرشفة محليًا، وتعذر حفظ Supabase: '+(e.message||e));return null}}
async function saveSmartCardDecisionRemote(){try{if(!window.SmartSchoolSupabase||!SmartSchoolSupabase.saveExternalEvaluationDecision)return null;return await SmartSchoolSupabase.saveExternalEvaluationDecision({visit_id:state.supabaseVisitId||null,final_score:finalScore(),decision:decisionText(finalScore())[0],strengths:[],gaps:[],recommendations:[],team_leader_name:state.teamLeaderName||state.leaderName||'',leader_signature_path:state.leaderSignaturePath||null})}catch(e){console.warn('تعذر حفظ قرار الاعتماد:',e);return null}}

function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
async function saveDraft(showMessage=false){state.archived=false;save();await saveSmartCardDraftRemote(false); if(showMessage) alert('تم حفظ مسودة الزيارة. يمكنك العودة لاحقًا لاستكمال التعبئة دون تثبيت رقم أرشيفي.')}
function load(){try{let s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'); if(s){Object.assign(state,s); state.school={...emptySchool(),...(s.school||{})}; state.surveyDetails={...state.surveyDetails,...(s.surveyDetails||{})}; state.sectionNotes=s.sectionNotes||{}; state.criteria=s.criteria||{}; state.sourceStatus=s.sourceStatus||state.sourceStatus; state.visitNumber=s.visitNumber||nextArchiveNumber(); state.archived=!!s.archived}}catch(e){}}
function initializeData(){importSchoolFromSelfEvaluation()}
async function exportToLibrary(){let archive=JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]');if(!state.archived){let committed=Number(localStorage.getItem(VISIT_COUNTER_KEY)||0)+1;localStorage.setItem(VISIT_COUNTER_KEY,String(committed));state.visitNumber=committed;state.archived=true;}let code=visitCode();archive=archive.filter(a=>a.id!==code);archive.push({id:code,name:'بطاقة فريق التقويم الخارجي الذكية '+code,date:new Date().toLocaleString('ar-SA'),score:finalScore(),status:'مؤرشفة'});localStorage.setItem(ARCHIVE_KEY,JSON.stringify(archive));save();await saveSmartCardVisitRemote(false);await saveSmartCardDecisionRemote();let blob=new Blob([document.documentElement.outerHTML],{type:'text/html;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`بطاقة_فريق_التقويم_الخارجي_الذكية_${code}.html`;a.click();updateAll();alert('تم تثبيت رقم الزيارة وأرشفتها: '+code)}
function resetAll(){if(confirm('بدء مسودة زيارة جديدة؟ لن يتم تثبيت رقم زيارة إلا عند الأرشفة.')){localStorage.removeItem(STORAGE_KEY);location.reload()}}
function lockVisit(){if(finalScore()<1)return alert('لا يمكن الاعتماد قبل إدخال درجات التقييم.');state.locked=true;save();updateAll();alert('تم اعتماد الزيارة وقفل النموذج.')}

async function uploadLeaderSignatureFile(file){
  try{
    if(!file || !window.SmartSchoolSupabase || !SmartSchoolSupabase.uploadExternalEvaluationFile) return null;
    const params=getVisitParams();
    const result=await SmartSchoolSupabase.uploadExternalEvaluationFile(file,{
      school_id:params.school_id,
      visit_id:state.supabaseVisitId||null,
      draft_id:state.supabaseDraftId||null,
      visit_number:params.visit_number,
      section_name:'توقيع رئيس الفريق',
      file_type:'signature'
    });
    if(result && result.path){
      state.leaderSignaturePath=result.path;
      state.leaderSignatureRecordId=result.record && result.record.id || null;
      save();
    }
    return result;
  }catch(e){
    console.warn('تعذر رفع توقيع رئيس الفريق إلى Supabase Storage:', e);
    alert('تم عرض التوقيع محليًا، لكن تعذر رفعه إلى Supabase Storage: '+(e.message||e));
    return null;
  }
}

function clearSignature(){state.signature=null;state.leaderSignaturePath=null;state.leaderSignatureRecordId=null;updateAll()}
$('#signatureInput').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024)return alert('الحد الأقصى 2MB');let r=new FileReader();r.onload=async ev=>{state.signature=ev.target.result;updateAll();await saveSmartCardDraftRemote(false);await uploadLeaderSignatureFile(file);};r.readAsDataURL(file);e.target.value=''});
document.addEventListener('click',e=>{let t=e.target.closest('.treeToggle');if(t&&!t.dataset.target)t.parentElement.classList.toggle('open');if(t&&t.dataset.target)switchSection(t.dataset.target);let i=e.target.closest('.treeItem');if(i)switchSection(i.dataset.target)});
load();updateAll();switchSection('dashboard');
