(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let box='inbox',messages=[],users=[],permissions={},currentUser={},libraryFiles=[],attachments=[],current=null;
const typeLabel=t=>({message:'رسالة',official:'تعميم رسمي',notice:'إشعار',action_request:'طلب إجراء'}[t]||'رسالة'),priorityLabel=p=>({normal:'عادية',important:'مهمة',urgent:'عاجلة'}[p]||p),fmt=d=>d?new Date(d).toLocaleString('ar-SA'):'—';
async function init(){try{const u=await InternalMessaging.call('users');users=u.users||[];permissions=u.permissions||{};currentUser=u.current||{};renderRoleGroups(u.roleCounts||{});await stats();await load();applyQuery()}catch(e){showError(e)}}
async function stats(){try{const s=await InternalMessaging.call('stats',{});$('#cInbox').textContent=s.inbox||0;$('#cUnread').textContent=s.unread||0;$('#cPinned').textContent=s.pinned||0;$('#cArchive').textContent=s.archive||0;$('#cSent').textContent=s.sent||0}catch(_){}}
async function load(){try{let d;if(box==='sent')d=await InternalMessaging.call('sent',{});else d=await InternalMessaging.call(box==='archive'?'archive':box==='pinned'?'pinned':'inbox',{box});messages=d.messages||[];draw()}catch(e){showError(e)}}
function filters(m){const q=$('#q').value.trim().toLowerCase(),type=$('#filterType').value,prio=$('#filterPriority').value,status=$('#filterStatus').value,hay=JSON.stringify(m).toLowerCase();if(q&&!hay.includes(q))return false;if(type&&m.message_type!==type)return false;if(prio&&m.priority!==prio)return false;if(status==='unread'&&m.read_at)return false;if(status==='ack'&&!m.acknowledged_at)return false;if(status==='pending_ack'&&(!m.require_ack||m.acknowledged_at))return false;return true}
function draw(){const a=messages.filter(filters);$('#rows').innerHTML=a.length?a.map(m=>`<div class="row ${m.read_at||box==='sent'?'':'unread'} ${m.pinned_at?'pinned':''}" data-id="${E(m.id)}"><div class="rowtop"><b>${m.pinned_at?'📌 ':''}${E(m.subject)}</b><span class="pill t-${E(m.message_type)}">${E(typeLabel(m.message_type))}</span></div><div>${box==='sent'?'إلى: '+E((m.internal_message_recipients||[]).map(x=>x.recipient_name).join('، ')):'من: '+E(m.sender_name)}</div><div class="meta">${fmt(m.created_at)} ${m.require_ack?' · يتطلب تأكيد الاطلاع':''}</div>${box==='sent'?`<div class="receipt">قراءة ${m.read_count||0}/${m.recipient_count||0} · تأكيد ${m.ack_count||0}/${m.recipient_count||0}</div>`:''}</div>`).join(''):'<div class="empty">لا توجد رسائل مطابقة</div>';$$('.row').forEach(r=>r.onclick=()=>openMsg(r.dataset.id))}
async function openMsg(id){try{const d=await InternalMessaging.call('read',{messageId:id});current=d;const m=d.message,rs=d.recipients||[],att=d.attachments||[],mine=d.recipientState;$('#reader').innerHTML=`<div class="reader-head"><div><div class="chips"><span class="pill t-${E(m.message_type)}">${E(typeLabel(m.message_type))}</span><span class="pill">${E(priorityLabel(m.priority))}</span>${m.require_ack?'<span class="pill warn">يتطلب تأكيد الاطلاع</span>':''}</div><h2>${E(m.subject)}</h2><div class="meta">من: ${E(m.sender_name)} — ${E(m.sender_role)} · ${fmt(m.created_at)}</div></div></div>${m.linked_title||m.linked_url?`<div class="linked"><b>🔗 مرتبط بـ:</b> ${E(m.linked_title||m.linked_module||'عنصر من المنصة')} ${m.linked_url?`<a href="${E(m.linked_url)}">فتح العنصر</a>`:''}</div>`:''}<div class="msgbody">${E(m.body)}</div>${m.due_at?`<div class="due">الموعد المطلوب: ${fmt(m.due_at)}</div>`:''}${att.length?`<section class="attachments"><h3>المرفقات</h3>${att.map(a=>`<button class="att" data-file="${E(a.file_id||'')}">📎 ${E(a.file_name)} <small>${E(a.source==='library'?'من مكتبة القسم':'مرفق')}</small></button>`).join('')}</section>`:''}<section class="thread"><h3>سلسلة المحادثة</h3>${(d.thread||[]).map(x=>`<div class="thread-msg"><b>${E(x.sender_name)}</b><span>${fmt(x.created_at)}</span><p>${E(x.body)}</p></div>`).join('')}</section>${box==='sent'?renderReceipts(rs,m):renderRecipientActions(m,mine)}<div class="actions reader-actions"><button class="primary" id="replyBtn">رد</button><button class="secondary" id="replyAllBtn">رد للجميع</button><button class="secondary" id="forwardBtn">إعادة توجيه</button>${permissions.convertTask&&!m.converted_task_id?'<button class="secondary" id="toTaskBtn">تحويل إلى تكليف</button>':''}${m.converted_task_id?'<span class="pill ok">تم تحويلها إلى تكليف</span>':''}</div>`;$$('.att').forEach(b=>b.onclick=()=>window.CloudFileEngine?.open(b.dataset.file).catch(e=>alert(e.message)));$('#replyBtn').onclick=()=>reply(false);$('#replyAllBtn').onclick=()=>reply(true);$('#forwardBtn').onclick=forwardMessage;if($('#toTaskBtn'))$('#toTaskBtn').onclick=convertTask;await load();await stats()}catch(e){showError(e)}}
function renderReceipts(rs,m){return `<section class="receipts"><h3>تأكيدات المستلمين</h3>${rs.map(r=>`<div class="receipt-row"><span>${E(r.recipient_name)} <small>${E(r.recipient_role)}</small></span><span>${r.read_at?'✅ قرأ '+fmt(r.read_at):'○ لم يقرأ'} ${m.require_ack?(r.acknowledged_at?' · ☑ أكد':' · ☐ لم يؤكد'):''} ${r.action_status&&r.action_status!=='none'?' · '+E(r.action_status):''}</span></div>`).join('')}</section>`}
function renderRecipientActions(m,s){if(!s)return'';return `<div class="actions recipient-actions">${m.require_ack&&!s.acknowledged_at?'<button class="primary" data-act="acknowledge">تأكيد الاطلاع</button>':''}${m.message_type==='action_request'?'<button class="secondary" data-status="accepted">قبول الإجراء</button><button class="secondary" data-status="in_progress">قيد التنفيذ</button><button class="primary" data-status="done">تم التنفيذ</button>':''}<button class="secondary" data-act="${s.pinned_at?'unpin':'pin'}">${s.pinned_at?'إلغاء التثبيت':'📌 تثبيت'}</button><button class="secondary" data-act="${s.archived_at?'unarchive-message':'archive-message'}">${s.archived_at?'إرجاع للوارد':'أرشفة'}</button><button class="secondary" data-act="mark-unread">تعليم كغير مقروء</button></div>`}
async function recipientAction(e){const b=e.target.closest('[data-act],[data-status]');if(!b||!current)return;try{if(b.dataset.status)await InternalMessaging.call('action-status',{messageId:current.message.id,status:b.dataset.status});else await InternalMessaging.call(b.dataset.act,{messageId:current.message.id});await openMsg(current.message.id)}catch(x){alert(x.message)}}
async function reply(all){if(!current)return;const m=current.message,rs=current.recipients||[];await openCompose();const wanted=new Set();if(String(m.sender_user_id)===String(currentUser.id)){rs.forEach(r=>r.recipient_user_id&&wanted.add(String(r.recipient_user_id)))}else{if(m.sender_user_id)wanted.add(String(m.sender_user_id));if(all)rs.forEach(r=>r.recipient_user_id&&String(r.recipient_user_id)!==String(currentUser.id)&&wanted.add(String(r.recipient_user_id)))}$$('#people input[type=checkbox]').forEach(x=>x.checked=wanted.has(String(x.value)));$('#subject').value=/^رد:/.test(m.subject)?m.subject:'رد: '+m.subject;$('#modal').dataset.parent=m.id;$('#modal').dataset.thread=m.thread_id||m.id}async function forwardMessage(){if(!current)return;const m=current.message;await openCompose();$('#subject').value=/^إعادة توجيه:/.test(m.subject)?m.subject:'إعادة توجيه: '+m.subject;$('#body').value='الرسالة الأصلية من: '+(m.sender_name||'')+'\nبتاريخ: '+fmt(m.created_at)+'\n\n'+m.body}
function renderRoleGroups(counts){const box=$('#groupRoles');box.innerHTML=Object.entries(counts).map(([r,c])=>`<label><input type="checkbox" value="${E(r)}"> ${E(r)} <small>(${c})</small></label>`).join('');$('#groupWrap').style.display=permissions.groupSend?'block':'none';$('#allSchoolWrap').style.display=permissions.allSchool?'block':'none';$('#officialOption').disabled=!permissions.official}
async function openCompose(){attachments=[];renderAttachments();renderPeople('');resetComposeMeta();$('#modal').style.display='flex'}
function resetComposeMeta(){delete $('#modal').dataset.parent;delete $('#modal').dataset.thread}
function renderPeople(q){q=(q||'').toLowerCase();$('#people').innerHTML=users.filter(u=>!q||`${u.full_name} ${u.role} ${u.email}`.toLowerCase().includes(q)).map(u=>`<label class="person"><input type="checkbox" value="${E(u.id)}"><span>${E(u.full_name||u.email)} <small>— ${E(u.role||'')}</small></span></label>`).join('')}
async function addDeviceFiles(files){if(!window.CloudFileEngine)return alert('محرك الملفات غير متاح');for(const file of [...files]){try{setComposeStatus('جارٍ رفع '+file.name+'...');const r=await CloudFileEngine.upload({file,ownershipScope:'user',moduleKey:'internal_messages',displayName:file.name,metadata:{source:'internal_messaging',pendingMessage:true}});attachments.push({fileId:r.file.id,name:r.file.display_name||file.name,source:'device'})}catch(e){alert(e.message)}}renderAttachments();setComposeStatus('')}
async function openLibrary(){if(!window.CloudFileEngine)return alert('محرك الملفات غير متاح');$('#library').style.display='flex';$('#libraryList').innerHTML='<div class="empty mini">جارٍ تحميل المكتبة...</div>';try{const r=await CloudFileEngine.list({ownershipScope:'user',limit:1000});const all=(r.files||[]).filter(x=>x.status==='active'),lib=all.filter(x=>/library|section_records_repository/i.test(String(x.module_key||''))||/library/i.test(String(x.record_type||''))||String(x.metadata?.source||'').includes('library'));libraryFiles=lib.length?lib:all;renderLibrary()}catch(e){$('#libraryList').innerHTML='<div class="empty mini">'+E(e.message)+'</div>'}}
function renderLibrary(){const q=$('#librarySearch').value.toLowerCase();$('#libraryList').innerHTML=libraryFiles.filter(f=>!q||String(f.display_name||f.original_name||'').toLowerCase().includes(q)).map(f=>`<label class="librow"><input type="checkbox" value="${E(f.id)}"><span>📎 ${E(f.display_name||f.original_name||'ملف')}</span><button type="button" data-open="${E(f.id)}">فتح</button></label>`).join('');$$('[data-open]').forEach(b=>b.onclick=e=>{e.preventDefault();CloudFileEngine.open(b.dataset.open)})}
function useLibrary(){const ids=$$('#libraryList input:checked').map(x=>x.value);ids.forEach(id=>{const f=libraryFiles.find(x=>String(x.id)===id);if(f&&!attachments.some(a=>a.fileId===id))attachments.push({fileId:id,name:f.display_name||f.original_name||'ملف',source:'library'})});$('#library').style.display='none';renderAttachments()}
function renderAttachments(){$('#attachmentList').innerHTML=attachments.map((a,i)=>`<span class="attach-chip">${a.source==='library'?'📚':'📎'} ${E(a.name)} <button data-rm="${i}">×</button></span>`).join('');$$('[data-rm]').forEach(b=>b.onclick=()=>{attachments.splice(Number(b.dataset.rm),1);renderAttachments()})}
function linkedFromQuery(){const p=new URLSearchParams(location.search);return {module:p.get('linkedModule')||'',recordType:p.get('linkedType')||'',recordId:p.get('linkedId')||'',title:p.get('linkedTitle')||'',url:p.get('linkedUrl')||''}}
async function send(){const ids=$$('#people input:checked').map(x=>x.value),roles=permissions.groupSend?$$('#groupRoles input:checked').map(x=>x.value):[],all=permissions.allSchool&&$('#allSchool').checked,subject=$('#subject').value.trim(),body=$('#body').value.trim();if((!ids.length&&!roles.length&&!all)||!subject||!body)return setComposeStatus('اختر المستلم وأدخل العنوان ونص الرسالة.',true);try{$('#send').disabled=true;const linked=linkedFromQuery();await InternalMessaging.call('send',{recipientIds:ids,recipientRoles:roles,allSchool:all,subject,body,priority:$('#priority').value,messageType:$('#messageType').value,requireAck:$('#requireAck').checked,dueAt:$('#dueAt').value?new Date($('#dueAt').value).toISOString():null,parentMessageId:$('#modal').dataset.parent||null,threadId:$('#modal').dataset.thread||null,attachments,linked});$('#modal').style.display='none';clearCompose();box='sent';activateBox('sent');await load();await stats()}catch(e){setComposeStatus(e.message,true)}finally{$('#send').disabled=false}}
function clearCompose(){$('#subject').value='';$('#body').value='';$('#dueAt').value='';$('#requireAck').checked=false;$('#allSchool').checked=false;$$('#groupRoles input').forEach(x=>x.checked=false);attachments=[];resetComposeMeta()}
function setComposeStatus(s,bad){$('#status').textContent=s;$('#status').className=bad?'bad':''}
async function convertTask(){if(!current||!permissions.convertTask)return;const m=current.message,rs=current.recipients||[],cand=[];if(m.sender_user_id&&String(m.sender_user_id)!==String(currentUser.id))cand.push({recipient_user_id:m.sender_user_id,recipient_name:m.sender_name,recipient_role:m.sender_role});rs.forEach(r=>{if(r.recipient_user_id&&String(r.recipient_user_id)!==String(currentUser.id)&&!cand.some(x=>String(x.recipient_user_id)===String(r.recipient_user_id)))cand.push(r)});if(!cand.length&&rs.length)cand.push(...rs);if(!cand.length)return alert('لا يوجد مستخدم يمكن إسناد التكليف إليه');let opts=cand.map((r,i)=>`${i+1}) ${r.recipient_name} — ${r.recipient_role}`).join('\n'),n=cand.length===1?1:Number(prompt('اختر رقم المستخدم الذي سيُسند إليه التكليف:\n'+opts)||0);if(!n||!cand[n-1])return;const r=cand[n-1];try{const d=await InternalMessaging.taskCall('create',{assignedTo:r.recipient_user_id,assigneeName:r.recipient_name,assigneeRole:r.recipient_role,title:m.subject,description:m.body,priority:m.priority==='urgent'?'urgent':m.priority==='important'?'high':'normal',dueDate:m.due_at?String(m.due_at).slice(0,10):null,moduleKey:'central_tasks',assignmentType:'partial',sourceOwner:'',metadata:{source:'internal_message',messageId:m.id,linkedModule:m.linked_module||'',linkedRecordType:m.linked_record_type||'',linkedRecordId:m.linked_record_id||'',linkedUrl:m.linked_url||''}});await InternalMessaging.call('mark-converted',{messageId:m.id,taskId:d.task.id});alert('تم إنشاء التكليف وربطه بالرسالة.');await openMsg(m.id)}catch(e){alert(e.message)}}
function activateBox(v){box=v;$$('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.box===v))}
function applyQuery(){const p=new URLSearchParams(location.search);if(p.get('compose')){openCompose().then(()=>{if(p.get('recipient'))$$('#people input').forEach(x=>x.checked=x.value===p.get('recipient'));if(p.get('subject'))$('#subject').value=p.get('subject');if(p.get('body'))$('#body').value=p.get('body')})}if(p.get('message'))openMsg(p.get('message'))}
function showError(e){console.error(e);$('#rows').innerHTML=`<div class="empty">${E(e.message||e)}</div>`}
$('#compose').onclick=openCompose;$('#cancel').onclick=()=>$('#modal').style.display='none';$('#send').onclick=send;$('#peopleSearch').oninput=e=>renderPeople(e.target.value);$('#q').oninput=draw;$('#filterType').onchange=draw;$('#filterPriority').onchange=draw;$('#filterStatus').onchange=draw;$('#deviceFiles').onchange=e=>addDeviceFiles(e.target.files);$('#libraryBtn').onclick=openLibrary;$('#libraryCancel').onclick=()=>$('#library').style.display='none';$('#libraryUse').onclick=useLibrary;$('#librarySearch').oninput=renderLibrary;$('#reader').addEventListener('click',recipientAction);$$('.nav button').forEach(b=>b.onclick=()=>{activateBox(b.dataset.box);load()});init();
})();