-- تطوير منظومة قياس الأثر وبنك قياس الأثر - الإصدار 2
-- نفّذ مرة واحدة بعد ملف SUPABASE_IMPACT_SURVEYS_SETUP.sql

alter table public.impact_surveys add column if not exists analysis_status text not null default 'pending';
alter table public.impact_surveys add column if not exists analysis_snapshot jsonb;
alter table public.impact_surveys add column if not exists closed_at timestamptz;
alter table public.impact_surveys add column if not exists archived_at timestamptz;

alter table public.impact_assessments add column if not exists status text not null default 'active';
alter table public.impact_assessments add column if not exists survey_score numeric default 0;
alter table public.impact_assessments add column if not exists response_count integer default 0;
alter table public.impact_assessments add column if not exists positive_rate numeric default 0;
alter table public.impact_assessments add column if not exists analysis jsonb not null default '{}'::jsonb;
alter table public.impact_assessments add column if not exists archived_at timestamptz;

create table if not exists public.impact_analysis_snapshots (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.impact_surveys(id) on delete cascade,
  school_id text not null,
  program_name text not null,
  response_count integer not null default 0,
  avg_score numeric not null default 0,
  positive_rate numeric not null default 0,
  impact_level text,
  confidence_level text,
  strongest_item jsonb,
  weakest_item jsonb,
  question_stats jsonb not null default '[]'::jsonb,
  analysis jsonb not null default '{}'::jsonb,
  created_by_role text,
  created_at timestamptz not null default now()
);
create index if not exists impact_analysis_school_idx on public.impact_analysis_snapshots(school_id,created_at desc);
create index if not exists impact_analysis_survey_idx on public.impact_analysis_snapshots(survey_id,created_at desc);

alter table public.impact_analysis_snapshots enable row level security;
drop policy if exists impact_analysis_platform_access on public.impact_analysis_snapshots;
create policy impact_analysis_platform_access on public.impact_analysis_snapshots for all to anon, authenticated using (true) with check (true);
grant select,insert,update,delete on public.impact_analysis_snapshots to anon, authenticated;
grant usage,select on sequence public.impact_analysis_snapshots_id_seq to anon, authenticated;

create or replace view public.vw_impact_bank_summary as
select a.school_id,a.id assessment_id,a.program_name,a.role,a.program_type,a.target_group,a.measure_date,a.avg_improvement,a.impact_level,a.status,a.survey_score,a.response_count,a.positive_rate,a.created_at,a.updated_at,
       count(distinct s.id) filter (where s.status <> 'archived') as survey_count,
       count(distinct n.id) as analysis_snapshot_count
from public.impact_assessments a
left join public.impact_surveys s on s.school_id=a.school_id and s.program_name=a.program_name
left join public.impact_analysis_snapshots n on n.school_id=a.school_id and n.program_name=a.program_name
group by a.school_id,a.id,a.program_name,a.role,a.program_type,a.target_group,a.measure_date,a.avg_improvement,a.impact_level,a.status,a.survey_score,a.response_count,a.positive_rate,a.created_at,a.updated_at;

grant select on public.vw_impact_bank_summary to anon, authenticated;
