-- محرك قياس الأثر والاستبانات السحابي
-- نفّذ الملف كاملاً مرة واحدة داخل Supabase > SQL Editor.

create table if not exists public.impact_surveys (
  id text primary key,
  public_token text not null unique,
  school_id text not null,
  program_name text not null,
  title text not null,
  audience text,
  role text,
  role_label text,
  template text default 'custom',
  questions jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('draft','active','closed','archived')),
  measure_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.impact_survey_responses (
  id bigint generated by default as identity primary key,
  survey_id text not null references public.impact_surveys(id) on delete cascade,
  school_id text not null,
  program_name text,
  respondent_name text,
  respondent_category text,
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.impact_assessments (
  id text primary key,
  school_id text not null,
  program_name text not null,
  role text,
  target_group text,
  program_type text,
  measure_date date,
  period_label text,
  metrics jsonb not null default '[]'::jsonb,
  avg_improvement numeric default 0,
  impact_level text,
  findings text,
  conclusion text,
  recommendations text,
  evidence jsonb not null default '[]'::jsonb,
  external_evaluation boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists impact_surveys_school_idx on public.impact_surveys(school_id, created_at desc);
create index if not exists impact_surveys_token_idx on public.impact_surveys(public_token);
create index if not exists impact_responses_survey_idx on public.impact_survey_responses(survey_id, created_at desc);
create index if not exists impact_responses_school_idx on public.impact_survey_responses(school_id, created_at desc);
create index if not exists impact_assessments_school_idx on public.impact_assessments(school_id, created_at desc);

create or replace function public.set_impact_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_impact_surveys_updated_at on public.impact_surveys;
create trigger trg_impact_surveys_updated_at
before update on public.impact_surveys
for each row execute function public.set_impact_updated_at();

drop trigger if exists trg_impact_assessments_updated_at on public.impact_assessments;
create trigger trg_impact_assessments_updated_at
before update on public.impact_assessments
for each row execute function public.set_impact_updated_at();

-- قراءة استبانة عامة بواسطة الرمز فقط، دون كشف قائمة الاستبانات.
create or replace function public.get_public_impact_survey(p_token text)
returns table (
  id text,
  public_token text,
  school_id text,
  program_name text,
  title text,
  audience text,
  role text,
  role_label text,
  template text,
  questions jsonb,
  status text,
  measure_date date,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select s.id, s.public_token, s.school_id, s.program_name, s.title, s.audience,
         s.role, s.role_label, s.template, s.questions, s.status,
         s.measure_date, s.created_at
  from public.impact_surveys s
  where s.public_token = p_token and s.status = 'active'
  limit 1;
$$;

-- استقبال الرد العام وربطه تلقائياً بالمدرسة والبرنامج من سجل الاستبانة.
create or replace function public.submit_public_impact_response(
  p_token text,
  p_respondent_name text,
  p_respondent_category text,
  p_answers jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_survey public.impact_surveys%rowtype;
  v_id bigint;
begin
  select * into v_survey
  from public.impact_surveys
  where public_token = p_token and status = 'active'
  limit 1;

  if v_survey.id is null then
    raise exception 'SURVEY_NOT_AVAILABLE';
  end if;

  insert into public.impact_survey_responses(
    survey_id, school_id, program_name,
    respondent_name, respondent_category, answers
  ) values (
    v_survey.id, v_survey.school_id, v_survey.program_name,
    nullif(trim(p_respondent_name),''), nullif(trim(p_respondent_category),''),
    coalesce(p_answers,'[]'::jsonb)
  ) returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.get_public_impact_survey(text) from public;
revoke all on function public.submit_public_impact_response(text,text,text,jsonb) from public;
grant execute on function public.get_public_impact_survey(text) to anon, authenticated;
grant execute on function public.submit_public_impact_response(text,text,text,jsonb) to anon, authenticated;

-- المنصة الحالية تستخدم تسجيل دخول داخلياً وليس Supabase Auth؛ لذلك تسمح السياسات
-- للواجهة الحالية بالإنشاء والقراءة، مع بقاء عزل school_id داخل التطبيق.
-- عند نقل تسجيل الدخول إلى Supabase Auth يجب استبدال هذه السياسات بسياسات auth.uid().
alter table public.impact_surveys enable row level security;
alter table public.impact_survey_responses enable row level security;
alter table public.impact_assessments enable row level security;

drop policy if exists impact_surveys_platform_access on public.impact_surveys;
create policy impact_surveys_platform_access on public.impact_surveys
for all to anon, authenticated using (true) with check (true);

drop policy if exists impact_responses_platform_read on public.impact_survey_responses;
create policy impact_responses_platform_read on public.impact_survey_responses
for select to anon, authenticated using (true);

-- الردود العامة تُضاف عبر RPC فقط، لذلك لا توجد سياسة INSERT مباشرة للجدول.
drop policy if exists impact_assessments_platform_access on public.impact_assessments;
create policy impact_assessments_platform_access on public.impact_assessments
for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.impact_surveys to anon, authenticated;
grant select on public.impact_survey_responses to anon, authenticated;
grant select, insert, update, delete on public.impact_assessments to anon, authenticated;
grant usage, select on sequence public.impact_survey_responses_id_seq to anon, authenticated;
