-- قاموس السجلات الموحد وربطه بمحرك التكليفات
begin;
insert into public.platform_modules(module_key,display_name,owner_role,route_url,is_active) values
('manager_records','الاتصالات الإدارية','manager','manager_records.html',true),
('meetings','الاجتماعات','manager','manager_records.html',true),
('committees','المجالس واللجان','manager','manager_records.html',true),
('staff_development','دعم وتطوير الهيئة التعليمية','manager','manager_records.html',true),
('circulars','النشرات والتبليغات','manager','manager_records.html',true),
('central_tasks','التكليفات والوصف الوظيفي','manager','central_task_center.html',true),
('operational_plan','الخطة التشغيلية وملف الشواهد','manager','manager_records.html',true),
('authorities','الصلاحيات','manager','manager_records.html',true),
('operational_budget','الميزانية التشغيلية','manager','manager_records.html',true),
('staff_followup','متابعة الهيئة التعليمية والإدارية','manager','manager_records.html',true),
('performance','الأداء الوظيفي','manager','school-performance-dashboard.html',true),
('school_information','البيانات الشاملة','manager','school_information_center.html',true),
('supervisor_visits','تقارير المشرفين/المشرفات','manager','supervisor_visit.html',true),
('recognition','التعزيز والتكريم','manager','manager_records.html',true),
('impact_assessment','قياس اتجاه المتعلمين نحو المدرسة','manager','impact_assessment.html',true),
('document_control','ضبط الوثائق','manager','manager_records.html',true),
('internal_audit','التدقيق الداخلي','manager','self_evaluation_records.html',true),
('international_exams','الاختبارات الدولية','manager','manager_exams_management.html',true),
('academic_affairs','الجداول المدرسية','deputy','wakil-records.html',true),
('student_affairs','المناوبة والإشراف اليومي','deputy','wakil-records.html',true),
('academic_achievement','التحصيل الدراسي والفاقد التعليمي','deputy','teacher_data_analysis.html',true),
('exams','ملف الاختبار العام','deputy','manager_exams_management.html',true),
('madrasati','منصة مدرستي','deputy','wakil-records.html',true),
('professional_growth','النمو المهني','deputy','wakil-records.html',true),
('gifted','ملف الموهوبين','deputy','wakil-records.html',true),
('special_education','التربية الخاصة','deputy','wakil-records.html',true),
('staff_affairs','سجل العمل الرسمي','deputy','wakil-records.html',true),
('school_operations','العهد والمستودعات والأرشفة','deputy','wakil-records.html',true),
('student_services','النقل المدرسي','deputy','wakil-records.html',true),
('learning_resources','المعامل والمختبرات والمصادر','deputy','wakil-records.html',true),
('reports','إعداد تقرير','manager','manager_records.html',true),
('forms','تعبئة نموذج','manager','manager_records.html',true),
('initiatives','متابعة مبادرة','manager','activity_leader_records.html',true),
('files','تحديث ملف','manager','cloud_files_center.html',true),
('archives','أرشفة مستندات','manager','manager_library_records.html',true),
('operations','تنفيذ مهمة تشغيلية','manager','assignment_workspace.html',true),
('health_guidance','التوجيه الصحي','manager','school_health_unified_registry.html',true),
('teacher_records','سجل المعلم الشامل','teacher','teacher_comprehensive_record.html',true),
('student_advisor','حالات التوجيه الطلابي','student_advisor','student_advisor_records.html',true),
('activity','سجلات رائد النشاط','activity_leader','activity_leader_records.html',true),
('administrative_employee','سجل الموظف الإداري','administrative_employee','administrative_employee_portal.html',true),
('school_readiness','بند الجاهزية','manager','school_readiness.html',true),
('self_evaluation','سجلات التقويم الذاتي','manager','self_evaluation_records.html',true),
('external_evaluation','أرشيف التقويم الخارجي','manager','external_evaluation_archive.html',true)
on conflict(module_key) do update set display_name=excluded.display_name,owner_role=excluded.owner_role,route_url=excluded.route_url,is_active=true;

insert into public.platform_record_types(module_key,record_type,display_name,route_url,is_assignable,supports_files,supports_approval,supports_analysis,configuration_json) values
('manager_records','administrative_communications','الاتصالات الإدارية','manager_records.html',true,true,true,true,'{"catalog_label": "الاتصالات الإدارية", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('meetings','meeting_record','الاجتماعات','manager_records.html',true,true,true,true,'{"catalog_label": "الاجتماعات", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('committees','committee_record','المجالس واللجان','manager_records.html',true,true,true,true,'{"catalog_label": "المجالس واللجان", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_development','staff_development_record','دعم وتطوير الهيئة التعليمية','manager_records.html',true,true,true,true,'{"catalog_label": "دعم وتطوير الهيئة التعليمية", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('circulars','circular_record','النشرات والتبليغات','manager_records.html',true,true,true,true,'{"catalog_label": "النشرات والتبليغات", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('central_tasks','central_task','التكليفات والوصف الوظيفي','central_task_center.html',true,true,true,true,'{"catalog_label": "التكليفات والوصف الوظيفي", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('operational_plan','operational_plan_record','الخطة التشغيلية وملف الشواهد','manager_records.html',true,true,true,true,'{"catalog_label": "الخطة التشغيلية وملف الشواهد", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('authorities','authority_record','الصلاحيات','manager_records.html',true,true,true,true,'{"catalog_label": "الصلاحيات", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('operational_budget','budget_record','الميزانية التشغيلية','manager_records.html',true,true,true,true,'{"catalog_label": "الميزانية التشغيلية", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_followup','staff_followup_record','متابعة الهيئة التعليمية والإدارية','manager_records.html',true,true,true,true,'{"catalog_label": "متابعة الهيئة التعليمية والإدارية", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('performance','performance_record','الأداء الوظيفي','school-performance-dashboard.html',true,true,true,true,'{"catalog_label": "الأداء الوظيفي", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('school_information','school_information_record','البيانات الشاملة','school_information_center.html',true,true,true,true,'{"catalog_label": "البيانات الشاملة", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('supervisor_visits','supervisor_visit_record','تقارير المشرفين/المشرفات','supervisor_visit.html',true,true,true,true,'{"catalog_label": "تقارير المشرفين/المشرفات", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('recognition','recognition_record','التعزيز والتكريم','manager_records.html',true,true,true,true,'{"catalog_label": "التعزيز والتكريم", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('impact_assessment','learner_attitude_record','قياس اتجاه المتعلمين نحو المدرسة','impact_assessment.html',true,true,true,true,'{"catalog_label": "قياس اتجاه المتعلمين نحو المدرسة", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('document_control','document_control_record','ضبط الوثائق','manager_records.html',true,true,true,true,'{"catalog_label": "ضبط الوثائق", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('internal_audit','internal_audit_record','التدقيق الداخلي','self_evaluation_records.html',true,true,true,true,'{"catalog_label": "التدقيق الداخلي", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('international_exams','international_exam_record','الاختبارات الدولية','manager_exams_management.html',true,true,true,true,'{"catalog_label": "الاختبارات الدولية", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('academic_affairs','school_schedule_record','الجداول المدرسية','wakil-records.html',true,true,true,true,'{"catalog_label": "الجداول المدرسية", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('academic_affairs','standby_classes_record','حصص الانتظار','wakil-records.html',true,true,true,true,'{"catalog_label": "حصص الانتظار", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('student_affairs','daily_supervision_record','المناوبة والإشراف اليومي','wakil-records.html',true,true,true,true,'{"catalog_label": "المناوبة والإشراف اليومي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('student_affairs','daily_supervision_report','تقرير المناوبة اليومي','wakil-records.html',true,true,true,true,'{"catalog_label": "تقرير المناوبة اليومي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('academic_affairs','study_plan_record','الخطط الدراسية','wakil-records.html',true,true,true,true,'{"catalog_label": "الخطط الدراسية", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_development','staff_development_record','دعم وتطوير الهيئة التعليمية','deputy_weekly_teacher_followup.html',true,true,true,true,'{"catalog_label": "دعم وتطوير الهيئة التعليمية", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_followup','teacher_admin_followup_record','متابعة أعمال المعلمين والإداريين','deputy_weekly_teacher_followup.html',true,true,true,true,'{"catalog_label": "متابعة أعمال المعلمين والإداريين", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('academic_achievement','achievement_loss_record','التحصيل الدراسي والفاقد التعليمي','teacher_data_analysis.html',true,true,true,true,'{"catalog_label": "التحصيل الدراسي والفاقد التعليمي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('exams','exam_record','ملف الاختبار العام','manager_exams_management.html',true,true,true,true,'{"catalog_label": "ملف الاختبار العام", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('international_exams','international_exam_record','ملف الاختبارات الدولية','agent_exams_management.html',true,true,true,true,'{"catalog_label": "ملف الاختبارات الدولية", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('madrasati','madrasati_record','منصة مدرستي','wakil-records.html',true,true,true,true,'{"catalog_label": "منصة مدرستي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('professional_growth','professional_growth_record','النمو المهني','wakil-records.html',true,true,true,true,'{"catalog_label": "النمو المهني", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('gifted','gifted_record','ملف الموهوبين','wakil-records.html',true,true,true,true,'{"catalog_label": "ملف الموهوبين", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('special_education','special_education_record','التربية الخاصة','wakil-records.html',true,true,true,true,'{"catalog_label": "التربية الخاصة", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_affairs','official_work_record','سجل العمل الرسمي','wakil-records.html',true,true,true,true,'{"catalog_label": "سجل العمل الرسمي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_affairs','staff_permission_record','استئذان الموظفين','wakil-records.html',true,true,true,true,'{"catalog_label": "استئذان الموظفين", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_affairs','staff_absence_record','حصر غياب الموظفين','wakil-records.html',true,true,true,true,'{"catalog_label": "حصر غياب الموظفين", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_affairs','staff_lateness_record','حصر دقائق التأخير','wakil-records.html',true,true,true,true,'{"catalog_label": "حصر دقائق التأخير", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('student_affairs','student_transfer_record','التحويلات','wakil-records.html',true,true,true,true,'{"catalog_label": "التحويلات", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('school_operations','custody_archive_record','العهد والمستودعات والأرشفة','wakil-records.html',true,true,true,true,'{"catalog_label": "العهد والمستودعات والأرشفة", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('school_operations','maintenance_cleaning_record','الصيانة والنظافة','wakil-records.html',true,true,true,true,'{"catalog_label": "الصيانة والنظافة", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('student_services','school_transport_record','النقل المدرسي','wakil-records.html',true,true,true,true,'{"catalog_label": "النقل المدرسي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('student_services','school_canteen_record','المقصف المدرسي','wakil-records.html',true,true,true,true,'{"catalog_label": "المقصف المدرسي", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('school_operations','facilities_record','المرافق','wakil-records.html',true,true,true,true,'{"catalog_label": "المرافق", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('learning_resources','labs_resources_record','المعامل والمختبرات والمصادر','wakil-records.html',true,true,true,true,'{"catalog_label": "المعامل والمختبرات والمصادر", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('school_operations','visitors_record','سجل الزائرات','wakil-records.html',true,true,true,true,'{"catalog_label": "سجل الزائرات", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_affairs','noor_leave_record','متابعة إدخال الإجازات في نظام نور','wakil-records.html',true,true,true,true,'{"catalog_label": "متابعة إدخال الإجازات في نظام نور", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('staff_affairs','fares_entry_record','متابعة الإدخال في نظام فارس','wakil-records.html',true,true,true,true,'{"catalog_label": "متابعة الإدخال في نظام فارس", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('student_affairs','student_affairs_record','سجلات شؤون الطلاب','wakil-records.html',true,true,true,true,'{"catalog_label": "سجلات شؤون الطلاب", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb),
('central_tasks','evidence_upload','رفع شاهد','assignment_workspace.html',true,true,true,true,'{"catalog_label": "رفع شاهد", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('reports','report_record','إعداد تقرير','manager_records.html',true,true,true,true,'{"catalog_label": "إعداد تقرير", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('forms','form_record','تعبئة نموذج','manager_records.html',true,true,true,true,'{"catalog_label": "تعبئة نموذج", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('initiatives','initiative_record','متابعة مبادرة','activity_leader_records.html',true,true,true,true,'{"catalog_label": "متابعة مبادرة", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('files','file_update_record','تحديث ملف','cloud_files_center.html',true,true,true,true,'{"catalog_label": "تحديث ملف", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('archives','archive_record','أرشفة مستندات','manager_library_records.html',true,true,true,true,'{"catalog_label": "أرشفة مستندات", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('operations','operational_task','تنفيذ مهمة تشغيلية','assignment_workspace.html',true,true,true,true,'{"catalog_label": "تنفيذ مهمة تشغيلية", "owner": "shared", "permission_scope": "record", "aliases": []}'::jsonb),
('health_guidance','health_record','التوجيه الصحي','school_health_unified_registry.html',true,true,true,true,'{"catalog_label": "التوجيه الصحي", "owner": "shared", "permission_scope": "module", "aliases": ["موجه صحي", "الموجه الصحي", "health_guidance"]}'::jsonb),
('learning_resources','lab_record','محضر المختبر','wakil-records.html',true,true,true,true,'{"catalog_label": "محضر المختبر", "owner": "shared", "permission_scope": "module", "aliases": ["مختبر"]}'::jsonb),
('learning_resources','learning_resources_record','مصادر التعلم','wakil-records.html',true,true,true,true,'{"catalog_label": "مصادر التعلم", "owner": "shared", "permission_scope": "module", "aliases": []}'::jsonb),
('teacher_records','teacher_comprehensive_record','سجل المعلم الشامل','teacher_comprehensive_record.html',true,true,true,true,'{"catalog_label": "سجل المعلم الشامل", "owner": "teacher", "permission_scope": "module", "aliases": []}'::jsonb),
('teacher_records','student_attendance_record','سجل حضور الطلاب','teacher_records_attendance.html',true,true,true,true,'{"catalog_label": "سجل حضور الطلاب", "owner": "teacher", "permission_scope": "module", "aliases": []}'::jsonb),
('teacher_records','student_participation_record','سجل المشاركة الصفية','teacher_records_participation.html',true,true,true,true,'{"catalog_label": "سجل المشاركة الصفية", "owner": "teacher", "permission_scope": "module", "aliases": []}'::jsonb),
('teacher_records','student_work_record','سجل أعمال الطلاب','teacher_records_student_work.html',true,true,true,true,'{"catalog_label": "سجل أعمال الطلاب", "owner": "teacher", "permission_scope": "module", "aliases": []}'::jsonb),
('student_advisor','student_case','حالات التوجيه الطلابي','student_advisor_records.html',true,true,true,true,'{"catalog_label": "حالات التوجيه الطلابي", "owner": "student_advisor", "permission_scope": "module", "aliases": []}'::jsonb),
('student_advisor','student_followup_analysis','تحليل المتابعة الطلابية','student_followup_analysis_updated.html',true,true,true,true,'{"catalog_label": "تحليل المتابعة الطلابية", "owner": "student_advisor", "permission_scope": "module", "aliases": []}'::jsonb),
('student_advisor','student_advisor_analysis','تحليل بيانات الموجه الطلابي','student_advisor_analysis_tool.html',true,true,true,true,'{"catalog_label": "تحليل بيانات الموجه الطلابي", "owner": "student_advisor", "permission_scope": "module", "aliases": []}'::jsonb),
('activity','activity_record','سجلات رائد النشاط','activity_leader_records.html',true,true,true,true,'{"catalog_label": "سجلات رائد النشاط", "owner": "activity_leader", "permission_scope": "module", "aliases": []}'::jsonb),
('administrative_employee','administrative_record','سجل الموظف الإداري','administrative_employee_portal.html',true,true,true,true,'{"catalog_label": "سجل الموظف الإداري", "owner": "admin_employee", "permission_scope": "module", "aliases": []}'::jsonb),
('administrative_employee','administrative_plan','خطة الموظف الإداري','administrative_employee_plan.html',true,true,true,true,'{"catalog_label": "خطة الموظف الإداري", "owner": "admin_employee", "permission_scope": "module", "aliases": []}'::jsonb),
('administrative_employee','administrative_execution','تنفيذ الموظف الإداري','administrative_employee_execution.html',true,true,true,true,'{"catalog_label": "تنفيذ الموظف الإداري", "owner": "admin_employee", "permission_scope": "module", "aliases": []}'::jsonb),
('administrative_employee','administrative_evaluation','تقييم الموظف الإداري','administrative_employee_evaluation.html',true,true,true,true,'{"catalog_label": "تقييم الموظف الإداري", "owner": "admin_employee", "permission_scope": "module", "aliases": []}'::jsonb),
('administrative_employee','administrative_improvement','خطة تحسين الموظف الإداري','administrative_employee_improvement.html',true,true,true,true,'{"catalog_label": "خطة تحسين الموظف الإداري", "owner": "admin_employee", "permission_scope": "module", "aliases": []}'::jsonb),
('school_readiness','readiness_task','بند الجاهزية','school_readiness.html',true,true,true,true,'{"catalog_label": "بند الجاهزية", "owner": "manager", "permission_scope": "record", "aliases": []}'::jsonb),
('self_evaluation','self_evaluation_record','سجلات التقويم الذاتي','self_evaluation_records.html',true,true,true,true,'{"catalog_label": "سجلات التقويم الذاتي", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('external_evaluation','external_evaluation_record','أرشيف التقويم الخارجي','external_evaluation_archive.html',true,true,true,true,'{"catalog_label": "أرشيف التقويم الخارجي", "owner": "manager", "permission_scope": "module", "aliases": []}'::jsonb),
('supervisor_visits','supervisor_visit_record','زيارة إشرافية','supervisor_visit.html',true,true,true,true,'{"catalog_label": "زيارة إشرافية", "owner": "manager", "permission_scope": "record", "aliases": []}'::jsonb),
('exams','exam_committee_record','لجان ونماذج الاختبارات','exam_committees_forms.html',true,true,true,true,'{"catalog_label": "لجان ونماذج الاختبارات", "owner": "agent", "permission_scope": "module", "aliases": []}'::jsonb)
on conflict(module_key,record_type) do update set display_name=excluded.display_name,route_url=excluded.route_url,is_assignable=true,supports_files=excluded.supports_files,supports_approval=excluded.supports_approval,supports_analysis=true,configuration_json=excluded.configuration_json,is_active=true;
commit;
