
const NS='smartSchoolCloudStorage';
const STATUS_LABELS={draft:'مسودة',active:'نشط',in_progress:'قيد التنفيذ',pending_approval:'بانتظار الاعتماد',returned:'معاد للتعديل',rejected:'مرفوض',approved:'معتمد',archived:'مؤرشف',withdrawn:'مسحوب',transferred:'منقول',canceled:'ملغي'};
const STATUS_CLASS={draft:'s-draft',active:'s-active',in_progress:'s-active',pending_approval:'s-pending',returned:'s-returned',rejected:'s-rejected',approved:'s-approved',archived:'s-archived',withdrawn:'s-withdrawn',transferred:'s-transferred',canceled:'s-canceled'};
const TERMINAL_STATUSES=['approved','rejected','withdrawn','archived','canceled'];
const OWNER_ALLOWED_TRANSITIONS={active:['withdrawn','transferred','archived'],in_progress:['withdrawn','transferred','archived'],pending_approval:['approved','returned','rejected','withdrawn','transferred'],returned:['withdrawn','transferred','archived'],rejected:['archived'],approved:['archived'],transferred:['withdrawn','transferred','archived','in_progress'],withdrawn:['archived']};
const ASSIGNEE_ALLOWED_TRANSITIONS={active:['in_progress','pending_approval'],transferred:['in_progress','pending_approval'],returned:['in_progress','pending_approval'],in_progress:['pending_approval']};
const MANAGER_RECORDS=['الاتصالات الإدارية','الاجتماعات','المجالس واللجان','دعم وتطوير الهيئة التعليمية','النشرات والتبليغات','التكليفات والوصف الوظيفي','الخطة التشغيلية وملف الشواهد','الصلاحيات','الميزانية التشغيلية','متابعة الهيئة التعليمية والإدارية','الأداء الوظيفي','البيانات الشاملة','تقارير المشرفين/المشرفات','التعزيز والتكريم','قياس اتجاه المتعلمين نحو المدرسة','ضبط الوثائق','التدقيق الداخلي','الاختبارات الدولية'];
const AGENT_RECORDS=['الجداول المدرسية','حصص الانتظار','المناوبة والإشراف اليومي','تقرير المناوبة اليومي','الخطط الدراسية','دعم وتطوير الهيئة التعليمية','متابعة أعمال المعلمين والإداريين','التحصيل الدراسي والفاقد التعليمي','ملف الاختبار العام','ملف الاختبارات الدولية','منصة مدرستي','النمو المهني','ملف الموهوبين','التربية الخاصة','سجل العمل الرسمي','استئذان الموظفين','حصر غياب الموظفين','حصر دقائق التأخير','التحويلات','العهد والمستودعات والأرشفة','الصيانة والنظافة','النقل المدرسي','المقصف المدرسي','المرافق','المعامل والمختبرات والمصادر','سجل الزائرات','متابعة إدخال الإجازات في نظام نور','متابعة الإدخال في نظام فارس','سجلات شؤون الطلاب'];
const SHARED_RECORDS=['رفع شاهد','إعداد تقرير','تعبئة نموذج','متابعة مبادرة','تحديث ملف','أرشفة مستندات','تنفيذ مهمة تشغيلية','التوجيه الصحي','محضر المختبر','مصادر التعلم'];
function qs(k){return new URLSearchParams(location.search).get(k)||''}function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function uid(){return 'task_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}function parse(v,d){try{return JSON.parse(v)}catch(e){return d}}function read(k,d){return parse(localStorage.getItem(k),d)}function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function currentSchoolId(){return localStorage.getItem('activeSchoolId')||localStorage.getItem('school_id')||localStorage.getItem('currentSchoolId')||'default_school'}
function mode(){return qs('mode')||'owner'}function role(){return qs('role')||qs('owner')||localStorage.getItem('smart_school_active_role')||'manager'}
function taskKey(){return 'central_school_tasks_'+currentSchoolId()}function tasks(){return read(taskKey(),[])}function saveTasks(a){write(taskKey(),a)}
function routeIndexKey(){return 'central_task_routes_'+currentSchoolId()}function notificationKey(){return 'central_task_notifications_'+currentSchoolId()}
function userKeys(u){let keys=[]; if(u&&u.id)keys.push('id:'+u.id); if(u&&u.email)keys.push('email:'+String(u.email).toLowerCase()); return keys}
function pushNotice(target,title,message,taskId,type){let notices=read(notificationKey(),[]); notices.unshift({id:'notice_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),task_id:taskId||'',target_id:target&&target.id||'',target_email:target&&target.email||'',target_role:target&&target.role||'',title:title||'تنبيه',message:message||'',type:type||'info',read:false,created_at:new Date().toISOString()}); write(notificationKey(),notices.slice(0,500));}
function ownerTarget(t){return {id:t.owner_id||'',email:t.owner_email||'',role:t.owner_role||'manager',name:t.owner_label||'صاحب الصلاحية'}}
function assigneeTarget(t){return {id:t.assignee_id||'',email:t.assignee_email||'',role:t.assignee_role||'',name:t.assignee_name||'المكلف'}}
function updateRouteIndex(t,oldUser){let idx=read(routeIndexKey(),{}); if(oldUser){userKeys(oldUser).forEach(k=>{idx[k]=(idx[k]||[]).filter(x=>x!==t.task_id)})} userKeys(assigneeTarget(t)).forEach(k=>{let arr=idx[k]||[]; if(!arr.includes(t.task_id))arr.push(t.task_id); idx[k]=arr}); write(routeIndexKey(),idx)}
function removeRouteIndex(t){let idx=read(routeIndexKey(),{}); userKeys(assigneeTarget(t)).forEach(k=>{idx[k]=(idx[k]||[]).filter(x=>x!==t.task_id)}); write(routeIndexKey(),idx)}
function actorKind(){return mode()==='assignee'?'assignee':'owner'}
function canTransition(t,next,actor){actor=actor||actorKind(); if(!t||!next)return false; if(t.status===next)return true; if(t.status==='archived')return false; let map=actor==='assignee'?ASSIGNEE_ALLOWED_TRANSITIONS:OWNER_ALLOWED_TRANSITIONS; return (map[t.status]||[]).includes(next)}
function safeTransition(t,next,action,note,actor){if(!canTransition(t,next,actor)){alert('لا يمكن نقل حالة التكليف من '+(STATUS_LABELS[t.status]||t.status)+' إلى '+(STATUS_LABELS[next]||next)+' في هذا السياق.');return false} t.status=next;t.updated_at=new Date().toISOString();addHistory(t,action||'تغيير الحالة',note||('تم تغيير الحالة إلى '+(STATUS_LABELS[next]||next)));return true}
function normalizeRole(r){r=String(r||'').toLowerCase(); if(['teacher','معلم','معلمة','performance'].includes(r))return 'teacher'; if(['admin','administrative','administrative_employee','إداري','employee'].includes(r))return 'admin_employee'; if(['agent','wakil','وكيل'].includes(r))return 'agent'; if(['student_advisor','counselor','موجه'].includes(r))return 'student_advisor'; if(['activity_leader','رائد'].includes(r))return 'activity_leader'; return r||'user'}
function roleLabel(r){return {teacher:'معلم/معلمة',admin_employee:'موظف/موظفة إدارية',agent:'وكيل/وكيلة',student_advisor:'موجه/موجهة طلابية',activity_leader:'رائد/رائدة نشاط'}[r]||'مستخدم'}
function currentOwnerLabel(){return normalizeRole(role())==='agent'?'الوكيل/الوكيلة':'المدير/المديرة'}
function collectUsers(){let out=[]; const keys=[NS+'_users','smartSchoolCloudStorage_users','smart_school_users','school_users','users','registered_users','school_members','administrative_employee_plans']; keys.forEach(k=>{let a=read(k,[]); if(Array.isArray(a)) out=out.concat(a.map(x=>k==='administrative_employee_plans'?Object.assign({},x,{role:'admin_employee',name:x.name||x.employeeName}):x))}); for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i); if(/users|school_members|accounts/i.test(k||'')){let a=read(k,[]); if(Array.isArray(a)) out=out.concat(a)}} let seen=new Set(); out=out.map(u=>({id:u.id||u.user_id||u.email||uid(),name:u.name||u.fullName||u.full_name||u.employeeName||u.email||'مستخدم',email:u.email||'',role:normalizeRole(u.role||u.dbRole||u.type),status:u.status||((u.active||u.isActive)?'active':'active'),schoolId:u.schoolId||u.school_id||currentSchoolId()})).filter(u=>u.status!=='deleted' && (!u.schoolId || String(u.schoolId)===String(currentSchoolId()))).filter(u=>{let key=String(u.id||u.email); if(seen.has(key))return false; seen.add(key); return true;}); if(!out.length) out=[{id:'demo_teacher',name:'معلم تجريبي',role:'teacher',email:''},{id:'demo_admin',name:'موظف إداري تجريبي',role:'admin_employee',email:''},{id:'demo_agent',name:'وكيل تجريبي',role:'agent',email:''}]; return out}
function currentAssigneeId(){return qs('uid')||qs('userId')||qs('emp')||localStorage.getItem('currentUserId')||localStorage.getItem('current_user_id')||''}function currentAssigneeEmail(){return (qs('email')||localStorage.getItem('currentUserEmail')||'').toLowerCase()}function isMine(t){let id=currentAssigneeId(), em=currentAssigneeEmail(); return (id&&String(t.assignee_id)===String(id)) || (em&&String(t.assignee_email||'').toLowerCase()===em)}
function normalizeExtraCode(v){v=String(v||'').trim(); let map={'التوجيه الصحي':'health_guidance','موجه صحي':'health_guidance','الموجه الصحي':'health_guidance','health_guidance':'health_guidance','health':'health_guidance','منسق الموهوبين':'gifted_coordinator','الموهوبين':'gifted_coordinator','منسق الجودة':'quality_coordinator','الجودة':'quality_coordinator','محضر المختبر':'lab_preparator','مختبر':'lab_preparator','مصادر التعلم':'learning_resources'};return map[v]||v}
function readRoleMap(){return read('smart_school_teacher_extra_roles_map',{})}function writeRoleMap(m){write('smart_school_teacher_extra_roles_map',m);write('smartSchoolCloudStorage_teacher_extra_roles_map',m)}
function updateTeacherExtraRole(user,code,add){if(!user||normalizeRole(user.role)!=='teacher')return; code=normalizeExtraCode(code); let map=readRoleMap(); let keys=[]; if(user.id)keys.push('id:'+user.id); if(user.email)keys.push('email:'+String(user.email).toLowerCase()); keys.forEach(k=>{let arr=Array.isArray(map[k])?map[k]:[]; arr=arr.map(normalizeExtraCode); if(add&&!arr.includes(code))arr.push(code); if(!add)arr=arr.filter(x=>x!==code); map[k]=arr}); writeRoleMap(map)}
function hasOtherActiveAdditionalRole(user,code,exceptTaskId){code=normalizeExtraCode(code);return tasks().some(x=>x.task_id!==exceptTaskId&&x.assignment_type==='additional_role'&&normalizeExtraCode(x.record_key)===code&&!['withdrawn','archived','rejected','canceled'].includes(x.status)&&userKeys(user).some(k=>userKeys(assigneeTarget(x)).includes(k)))}
function routeTaskToAssignee(t,oldUser){let u=assigneeTarget(t); updateRouteIndex(t,oldUser); if(t.assignment_type==='additional_role'){updateTeacherExtraRole(u,t.record_key,true); if(oldUser&&!hasOtherActiveAdditionalRole(oldUser,t.record_key,t.task_id)) updateTeacherExtraRole(oldUser,t.record_key,false)} pushNotice(u,'تكليف جديد أو منقول','تم إسناد التكليف: '+t.title,u.task_id||t.task_id,'assigned')}
function removeTaskRoute(t){let u=assigneeTarget(t); removeRouteIndex(t); if(t.assignment_type==='additional_role'&&!hasOtherActiveAdditionalRole(u,t.record_key,t.task_id)) updateTeacherExtraRole(u,t.record_key,false)}
function populateRecords(){let owner=document.getElementById('sourceOwner').value; let arr=owner==='manager'?MANAGER_RECORDS:(owner==='agent'?AGENT_RECORDS:SHARED_RECORDS); document.getElementById('recordKey').innerHTML=arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function populateUsers(){let users=collectUsers(); document.getElementById('assigneeId').innerHTML=users.map(u=>`<option value="${esc(u.id)}" data-role="${esc(u.role)}" data-email="${esc(u.email)}">${esc(u.name)} — ${esc(roleLabel(u.role))}</option>`).join('')}
function resetForm(){document.getElementById('taskForm').reset(); const today=new Date().toISOString().slice(0,10); document.getElementById('startDate').value=today; populateRecords()}
function switchView(v){document.querySelectorAll('.tab').forEach(b=>{b.classList.remove('active');b.classList.add('bg-white','text-slate-600')}); const btn=document.querySelector(`[data-view="${v}"]`); if(btn){btn.classList.add('active');btn.classList.remove('bg-white','text-slate-600')} document.getElementById('createView').classList.toggle('hidden',v!=='create');document.getElementById('listView').classList.toggle('hidden',v==='create'||v==='analytics'); const av=document.getElementById('analyticsView'); if(av) av.classList.toggle('hidden',v!=='analytics'); window.currentView=v; if(v==='analytics') renderAnalytics(); else if(v!=='create') renderList()}
function getTask(id){return tasks().find(t=>t.task_id===id)}function setTask(next){saveTasks(tasks().map(t=>t.task_id===next.task_id?next:t));renderAll()}
function addHistory(t,action,note){t.history=t.history||[];t.history.unshift({at:new Date().toISOString(),action,by:mode()==='assignee'?'المكلف':currentOwnerLabel(),actor:actorKind(),status:t.status||'',note:note||''});return t}
function createTask(e){e.preventDefault(); const users=collectUsers(); const sel=document.getElementById('assigneeId'); const assignee=users.find(u=>String(u.id)===String(sel.value))||{}; const t={task_id:uid(),school_id:currentSchoolId(),title:document.getElementById('taskTitle').value,description:document.getElementById('taskDesc').value,assignment_type:document.getElementById('taskType').value,source_owner:document.getElementById('sourceOwner').value,record_key:document.getElementById('recordKey').value,owner_role:normalizeRole(role()),owner_label:currentOwnerLabel(),owner_id:localStorage.getItem('currentUserId')||role(),owner_email:localStorage.getItem('currentUserEmail')||'',assignee_id:assignee.id,assignee_email:assignee.email,assignee_name:assignee.name,assignee_role:assignee.role,priority:document.getElementById('priority').value,start_date:document.getElementById('startDate').value,due_date:document.getElementById('dueDate').value,status:'active',created_at:new Date().toISOString(),updated_at:new Date().toISOString(),pending_updates:[],evidence:[],history:[]}; addHistory(t,'إنشاء التكليف','تم إنشاء التكليف وربطه بالمكلف الحالي.'); let a=tasks(); a.unshift(t); saveTasks(a); routeTaskToAssignee(t); resetForm(); switchView('active')}
function renderSummary(){let m=analyticsMetrics(visibleTasks()); document.getElementById('summaryCards').innerHTML=[['التكليفات النشطة',m.active,'⚙️','text-teal-700'],['المتأخرة',m.overdue,'🚨',m.overdue?'text-red-600':'text-emerald-700'],['بانتظار الاعتماد',m.pending,'⏳','text-amber-600'],['نسبة الإنجاز',m.completion+'%','✅','text-emerald-700']].map(x=>`<div class="bg-white rounded-[26px] p-5 border border-white shadow-sm card-hover"><div class="flex justify-between items-center"><div><p class="text-xs text-slate-500 font-black">${x[0]}</p><h3 class="text-3xl font-black ${x[3]} mt-1">${x[1]}</h3></div><div class="text-3xl">${x[2]}</div></div></div>`).join('')}
function visibleTasks(){let a=tasks(); if(mode()==='assignee') return a.filter(isMine).filter(t=>!['withdrawn','archived'].includes(t.status)); return a}
function filterByView(t,v){if(mode()==='assignee')return !['withdrawn','archived','canceled'].includes(t.status); if(v==='active')return ['active','in_progress','transferred'].includes(t.status); if(v==='pending')return t.status==='pending_approval'; if(v==='returned')return t.status==='returned'; if(v==='withdrawn')return t.status==='withdrawn'; if(v==='rejected')return t.status==='rejected'; if(v==='approved')return t.status==='approved'; if(v==='archived')return t.status==='archived'; return true}
function renderList(){let v=window.currentView||'active'; document.getElementById('listTitle').innerText=mode()==='assignee'?'تكليفاتي':({active:'التكليفات النشطة',pending:'بانتظار الاعتماد',returned:'المعادة للتعديل',withdrawn:'المسحوبة',rejected:'المرفوضة',approved:'المعتمدة',archived:'الأرشيف'}[v]||'التكليفات'); let q=(document.getElementById('searchBox')?.value||'').trim().toLowerCase(); let arr=visibleTasks().filter(t=>filterByView(t,v)).filter(t=>!q||JSON.stringify(t).toLowerCase().includes(q)); document.getElementById('tasksList').innerHTML=arr.length?arr.map(taskCard).join(''):'<div class="text-center p-10 text-slate-400 font-black border border-dashed rounded-[28px] bg-white/70">لا توجد تكليفات في هذا التصنيف.</div>'}
function taskCard(t){let canAct=t.status!=='archived'; let assignee=mode()==='assignee'; let ownerBtns=`<button onclick="openReassign('${t.task_id}')" class="px-3 py-2 rounded-xl bg-blue-50 text-blue-700 text-xs font-black">نقل</button><button onclick="withdrawTask('${t.task_id}')" class="px-3 py-2 rounded-xl bg-slate-100 text-slate-700 text-xs font-black">سحب</button><button onclick="approveTask('${t.task_id}')" class="px-3 py-2 rounded-xl bg-green-50 text-green-700 text-xs font-black">اعتماد</button><button onclick="returnTask('${t.task_id}')" class="px-3 py-2 rounded-xl bg-amber-50 text-amber-700 text-xs font-black">إعادة للتعديل</button><button onclick="rejectTask('${t.task_id}')" class="px-3 py-2 rounded-xl bg-red-50 text-red-700 text-xs font-black">رفض</button><button onclick="archiveTask('${t.task_id}')" class="px-3 py-2 rounded-xl bg-slate-800 text-white text-xs font-black">أرشفة</button>`; let assigneeBtns=`<button onclick="startWork('${t.task_id}')" class="px-3 py-2 rounded-xl bg-blue-50 text-blue-700 text-xs font-black">بدء/متابعة</button><button onclick="openSubmit('${t.task_id}')" class="px-3 py-2 rounded-xl bg-teal-600 text-white text-xs font-black">رفع تنفيذ/شاهد</button><button onclick="submitForApproval('${t.task_id}')" class="px-3 py-2 rounded-xl bg-amber-50 text-amber-700 text-xs font-black">إرسال للاعتماد</button>`; return `<article class="bg-white rounded-[28px] p-5 border border-slate-100 card-hover"><div class="flex flex-col md:flex-row md:items-start justify-between gap-4"><div class="space-y-2"><div class="flex flex-wrap gap-2 items-center"><h3 class="font-black text-lg text-slate-800">${esc(t.title)}</h3><span class="status ${STATUS_CLASS[t.status]||'s-active'}">${STATUS_LABELS[t.status]||t.status}</span></div><p class="text-xs text-slate-500 font-bold">${esc(t.record_key)} — ${esc(t.owner_label)} → ${esc(t.assignee_name)} (${esc(roleLabel(t.assignee_role))})</p><p class="text-sm text-slate-600 leading-7">${esc(t.description||'لا يوجد وصف.')}</p><div class="flex flex-wrap gap-2 text-[11px] font-black"><span class="bg-slate-50 px-3 py-1 rounded-full">الأولوية: ${esc(t.priority)}</span><span class="bg-slate-50 px-3 py-1 rounded-full">البداية: ${esc(t.start_date||'-')}</span><span class="bg-slate-50 px-3 py-1 rounded-full">النهاية: ${esc(t.due_date||'-')}</span><span class="bg-slate-50 px-3 py-1 rounded-full">الأعمال المرفوعة: ${(t.pending_updates||[]).length}</span></div></div><div class="flex flex-wrap gap-2 no-print">${canAct?(assignee?assigneeBtns:ownerBtns):''}<button onclick="showHistory('${t.task_id}')" class="px-3 py-2 rounded-xl bg-teal-50 text-teal-700 text-xs font-black">السجل التاريخي</button></div></div></article>`}
function closeModal(){document.getElementById('modal').classList.add('hidden');document.getElementById('modal').classList.remove('flex')}function openModal(title,body){document.getElementById('modalTitle').innerText=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.remove('hidden');document.getElementById('modal').classList.add('flex')}
function openReassign(id){let t=getTask(id); if(!t)return; if(!canTransition(t,'transferred','owner')){alert('لا يمكن نقل هذا التكليف في حالته الحالية.');return} let users=collectUsers().filter(u=>String(u.id)!==String(t.assignee_id)); openModal('نقل التكليف',`<div class="space-y-3"><p class="text-sm text-slate-600 font-bold">سيبقى عمل المكلف السابق محفوظًا في الأرشيف، وتُسحب صلاحياته تلقائيًا.</p><select id="newAssignee" class="w-full rounded-2xl border px-4 py-3 text-sm">${users.map(u=>`<option value="${esc(u.id)}">${esc(u.name)} — ${esc(roleLabel(u.role))}</option>`).join('')}</select><textarea id="transferNote" class="w-full rounded-2xl border px-4 py-3 text-sm" placeholder="سبب النقل"></textarea><button onclick="reassignTask('${id}')" class="w-full bg-blue-600 text-white rounded-2xl py-3 font-black">تأكيد النقل</button></div>`)}
function reassignTask(id){let t=getTask(id); let users=collectUsers(); let nu=users.find(u=>String(u.id)===String(document.getElementById('newAssignee').value)); if(!t||!nu)return; let old=assigneeTarget(t); let reason=document.getElementById('transferNote').value||'نقل التكليف'; t.previous_assignees=t.previous_assignees||[]; t.previous_assignees.unshift({id:t.assignee_id,email:t.assignee_email,name:t.assignee_name,role:t.assignee_role,ended_at:new Date().toISOString(),reason:reason,preserved_updates:t.pending_updates||[],preserved_evidence:t.evidence||[]}); t.access_revoked=t.access_revoked||[]; t.access_revoked.unshift({id:old.id,email:old.email,name:old.name,role:old.role,at:new Date().toISOString(),reason:reason}); t.assignee_id=nu.id;t.assignee_email=nu.email;t.assignee_name=nu.name;t.assignee_role=nu.role; if(!safeTransition(t,'transferred','نقل التكليف','تم نقل التكليف إلى '+nu.name+' مع حفظ أعمال المنفذ السابق وسحب صلاحياته.','owner'))return; setTask(t); routeTaskToAssignee(t,old); pushNotice(old,'سحب صلاحية تكليف','تم نقل التكليف "'+t.title+'" إلى مكلف آخر، وبقي عملك السابق محفوظًا.',t.task_id,'revoked'); closeModal(); switchView('active')}
function withdrawTask(id){let t=getTask(id); if(!t)return; if(!confirm('سيتم سحب التكليف وإلغاء وصول المكلف الحالي مع حفظ الأعمال السابقة. هل تريد المتابعة؟'))return; let old=assigneeTarget(t); removeTaskRoute(t); t.access_revoked=t.access_revoked||[]; t.access_revoked.unshift({id:old.id,email:old.email,name:old.name,role:old.role,at:new Date().toISOString(),reason:'سحب التكليف'}); if(!safeTransition(t,'withdrawn','سحب التكليف','تم سحب صلاحية المنفذ الحالي مع حفظ الأعمال السابقة.','owner'))return; setTask(t); pushNotice(old,'تم سحب التكليف','تم سحب التكليف "'+t.title+'" من واجهتك مع حفظ أعمالك السابقة.',t.task_id,'withdrawn'); switchView('withdrawn')}
function approveTask(id){let t=getTask(id); if(!t)return; if(!canTransition(t,'approved','owner')){alert('لا يظهر زر الاعتماد إلا للتكليفات المرسلة بانتظار الاعتماد.');return} (t.pending_updates||[]).forEach(u=>{if(u.status!=='rejected')u.status='approved'}); t.approved_updates=(t.approved_updates||[]).concat((t.pending_updates||[]).filter(u=>u.status==='approved')); if(!safeTransition(t,'approved','اعتماد','تم اعتماد التكليف ودمج الأعمال المعتمدة في السجل الرسمي حسب الصلاحية.','owner'))return; setTask(t); pushNotice(assigneeTarget(t),'تم اعتماد التكليف','تم اعتماد التكليف "'+t.title+'".',t.task_id,'approved'); switchView('approved')}
function returnTask(id){let t=getTask(id); if(!t)return; if(!canTransition(t,'returned','owner')){alert('إعادة التعديل متاحة فقط للتكليفات بانتظار الاعتماد.');return} let note=prompt('ملاحظات الإعادة للتعديل:')||''; if(!safeTransition(t,'returned','إعادة للتعديل',note,'owner'))return; setTask(t); pushNotice(assigneeTarget(t),'أعيد التكليف للتعديل',note||('أعيد التكليف "'+t.title+'" للتعديل.'),t.task_id,'returned'); switchView('returned')}
function rejectTask(id){let t=getTask(id); if(!t)return; if(!canTransition(t,'rejected','owner')){alert('الرفض النهائي متاح فقط للتكليفات بانتظار الاعتماد.');return} let note=prompt('سبب الرفض النهائي:')||''; (t.pending_updates||[]).forEach(u=>{if(u.status!=='approved')u.status='rejected'}); if(!safeTransition(t,'rejected','رفض نهائي',note,'owner'))return; setTask(t); pushNotice(assigneeTarget(t),'تم رفض التكليف',note||('تم رفض التكليف "'+t.title+'".'),t.task_id,'rejected'); switchView('rejected')}
function archiveTask(id){let t=getTask(id); if(!t)return; if(!canTransition(t,'archived','owner')){alert('لا يمكن أرشفة هذا التكليف في حالته الحالية. اعتمده أو ارفضه أو اسحبه أولًا.');return} if(!safeTransition(t,'archived','أرشفة','تمت أرشفة التكليف دون حذف أي عمل سابق.','owner'))return; setTask(t); switchView('archived')}
function startWork(id){let t=getTask(id); if(!t)return; if(['active','transferred','returned'].includes(t.status)){if(!safeTransition(t,'in_progress','بدء التنفيذ','بدأ المكلف العمل على التكليف.','assignee'))return;setTask(t)} if(t.assignment_type==='additional_role' && normalizeExtraCode(t.record_key)==='health_guidance') location.href='school_health_unified_registry.html?source=central_task&task_id='+encodeURIComponent(id);}
function openSubmit(id){let t=getTask(id); if(!t)return; if(!['active','transferred','returned','in_progress'].includes(t.status)){alert('لا يمكن رفع تنفيذ في هذه الحالة.');return} openModal('رفع تنفيذ أو شاهد',`<form onsubmit="saveUpdate(event,'${id}')" class="space-y-3"><input id="updTitle" required class="w-full rounded-2xl border px-4 py-3 text-sm" placeholder="عنوان التنفيذ"><textarea id="updDesc" class="w-full rounded-2xl border px-4 py-3 text-sm" placeholder="وصف التنفيذ أو ملاحظاته"></textarea><input id="updLink" class="w-full rounded-2xl border px-4 py-3 text-sm" placeholder="رابط داعم اختياري"><input id="updFile" type="file" class="w-full rounded-2xl border px-4 py-3 text-sm"><button class="w-full bg-teal-600 text-white rounded-2xl py-3 font-black">حفظ التنفيذ</button></form>`)}
function saveUpdate(e,id){e.preventDefault();let t=getTask(id); if(!t)return; let f=document.getElementById('updFile').files[0]; let item={id:'upd_'+Date.now(),title:document.getElementById('updTitle').value,desc:document.getElementById('updDesc').value,link:document.getElementById('updLink').value,file:f?{name:f.name,size:f.size,type:f.type}:null,by:t.assignee_name,at:new Date().toISOString(),status:'draft'}; t.pending_updates=t.pending_updates||[];t.pending_updates.unshift(item); if(t.status!=='in_progress'){if(!safeTransition(t,'in_progress','رفع تنفيذ/شاهد',item.title,'assignee'))return}else addHistory(t,'رفع تنفيذ/شاهد',item.title); t.updated_at=new Date().toISOString();setTask(t);closeModal();renderList()}
function submitForApproval(id){let t=getTask(id); if(!t)return; if(!canTransition(t,'pending_approval','assignee')){alert('لا يمكن إرسال هذا التكليف للاعتماد في حالته الحالية.');return} if(!(t.pending_updates||[]).length&&!confirm('لم يتم رفع أي تنفيذ أو شاهد. هل تريد الإرسال للاعتماد؟'))return; (t.pending_updates||[]).forEach(u=>{if(u.status==='draft')u.status='pending_approval'}); if(!safeTransition(t,'pending_approval','إرسال للاعتماد','أرسل المكلف العمل إلى صاحب الصلاحية للمراجعة.','assignee'))return; setTask(t); pushNotice(ownerTarget(t),'تكليف بانتظار الاعتماد','أرسل '+(t.assignee_name||'المكلف')+' التكليف "'+t.title+'" للاعتماد.',t.task_id,'pending_approval'); renderList()}
function showHistory(id){let t=getTask(id); if(!t)return; let prev=(t.previous_assignees||[]).map(p=>`<div class="bg-blue-50 rounded-2xl p-3 mb-2 text-xs font-bold text-blue-900">منفذ سابق: ${esc(p.name)} — ${new Date(p.ended_at).toLocaleString('ar-SA')} — السبب: ${esc(p.reason||'')}</div>`).join(''); let hist=(t.history||[]).map(h=>`<div class="audit-line bg-slate-50 rounded-2xl p-3 mb-2"><div class="font-black text-slate-800 text-sm">${esc(h.action)} <span class="text-[10px] text-teal-700">${esc(STATUS_LABELS[h.status]||h.status||'')}</span></div><div class="text-xs text-slate-500 font-bold">${new Date(h.at).toLocaleString('ar-SA')} — ${esc(h.by)}</div><p class="text-xs text-slate-600 mt-1">${esc(h.note||'')}</p></div>`).join(''); openModal('السجل التاريخي للتكليف',prev+hist||'<p class="text-slate-400 text-center font-bold">لا توجد أحداث.</p>')}

function parseDateSafe(v){let d=v?new Date(v):null; return d&& !isNaN(d)?d:null}
function todayOnly(){let d=new Date(); d.setHours(0,0,0,0); return d}
function taskWeight(t){return t.assignment_type==='additional_role'?3:(t.assignment_type==='record'?2:1)}
function isOverdue(t){let d=parseDateSafe(t.due_date); if(!d)return false; d.setHours(0,0,0,0); return d<todayOnly()&&!['approved','archived','withdrawn','rejected','canceled'].includes(t.status)}
function analyticsMetrics(arr){arr=arr||[]; let activeStatuses=['active','in_progress','pending_approval','returned','transferred']; let actionable=arr.filter(t=>!['draft','archived','canceled'].includes(t.status)); let approved=arr.filter(t=>t.status==='approved').length; let completionDen=arr.filter(t=>!['draft','archived','canceled','withdrawn'].includes(t.status)).length||0; let weightedDone=arr.filter(t=>t.status==='approved').reduce((s,t)=>s+taskWeight(t),0); let weightedTotal=arr.filter(t=>!['draft','archived','canceled','withdrawn'].includes(t.status)).reduce((s,t)=>s+taskWeight(t),0); let avgDays=avgCompletionDays(arr); return {total:arr.length,active:arr.filter(t=>activeStatuses.includes(t.status)).length,pending:arr.filter(t=>t.status==='pending_approval').length,returned:arr.filter(t=>t.status==='returned').length,rejected:arr.filter(t=>t.status==='rejected').length,approved,overdue:arr.filter(isOverdue).length,completion:completionDen?Math.round(approved/completionDen*100):0,weighted:weightedTotal?Math.round(weightedDone/weightedTotal*100):0,avgDays}}
function avgCompletionDays(arr){let vals=arr.filter(t=>t.status==='approved').map(t=>{let s=parseDateSafe(t.created_at||t.start_date), e=parseDateSafe(t.updated_at); return s&&e?Math.max(0,(e-s)/86400000):null}).filter(x=>x!==null); return vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1):'--'}
function groupCount(arr,fn){let m={}; arr.forEach(t=>{let k=fn(t)||'غير محدد'; m[k]=(m[k]||0)+1}); return m}
function groupWeighted(arr,fn){let m={}; arr.forEach(t=>{let k=fn(t)||'غير محدد'; m[k]=(m[k]||0)+taskWeight(t)+(isOverdue(t)?1.5:0)}); return m}
function pct(n,d){return d?Math.round(n/d*100):0}
function renderBars(elId,map,opts){let entries=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,(opts&&opts.limit)||6); let max=Math.max(1,...entries.map(x=>x[1])); document.getElementById(elId).innerHTML=entries.length?entries.map(([k,v],i)=>`<div class="bar-row"><div class="text-xs font-black text-slate-600 truncate" title="${esc(k)}">${esc(k)}</div><div class="bar-track"><div class="bar-fill ${i===0&&v>max*.7?'warn':''}" style="--w:${Math.max(5,Math.round(v/max*100))}%"></div></div><div class="text-xs font-black text-slate-700 text-left">${Math.round(v)}</div></div>`).join(''):'<div class="text-center text-slate-400 font-black p-8">لا توجد بيانات كافية.</div>'}
function renderAnalytics(){let arr=visibleTasks(); let m=analyticsMetrics(arr); let kpis=[{label:'التكليفات النشطة',num:m.active,sub:'تشمل قيد التنفيذ وبانتظار الاعتماد',icon:'⚙️',accent:'rgba(20,184,166,.16)',w:pct(m.active,Math.max(1,m.total))},{label:'التكليفات المتأخرة',num:m.overdue,sub:m.overdue?'تحتاج تدخلًا إداريًا عاجلًا':'لا توجد تكليفات متأخرة',icon:'🚨',accent:'rgba(220,38,38,.14)',w:pct(m.overdue,Math.max(1,m.total))},{label:'المعتمدة',num:m.approved,sub:'نسبة الإنجاز العامة '+m.completion+'%',icon:'✅',accent:'rgba(22,163,74,.14)',w:m.completion},{label:'الإنجاز الموزون',num:m.weighted+'%',sub:'يعطي وزنًا أعلى للسجلات والأدوار الإضافية',icon:'📊',accent:'rgba(37,99,235,.12)',w:m.weighted}]; document.getElementById('execKpis').innerHTML=kpis.map(x=>`<div class="kpi-exec" style="--accent:${x.accent}"><div class="flex items-start justify-between"><div><div class="kpi-label">${x.label}</div><div class="kpi-number mt-2">${x.num}</div></div><div class="text-3xl">${x.icon}</div></div><div class="kpi-sub">${x.sub}</div><div class="spark"><span style="--w:${Math.min(100,Math.max(3,x.w))}%"></span></div></div>`).join('');
let roleMap=groupWeighted(arr.filter(t=>!['archived','canceled'].includes(t.status)),t=>roleLabel(t.assignee_role||'user')); renderBars('roleWorkloadChart',roleMap,{limit:6});
let counts={approved:m.approved,pending:m.pending,returned:m.returned,rejected:m.rejected+arr.filter(isOverdue).length,other:Math.max(0,m.total-m.approved-m.pending-m.returned-m.rejected)}; let total=Math.max(1,m.total); let degA=counts.approved/total*360, degP=counts.pending/total*360, degR=(counts.rejected)/total*360; let donut=document.getElementById('statusDonut'); donut.style.setProperty('--approved',degA+'deg'); donut.style.setProperty('--pending',degP+'deg'); donut.style.setProperty('--risk',degR+'deg'); document.getElementById('donutTotal').innerText=m.total; document.getElementById('statusLegend').innerHTML=`<div><span class="legend-dot" style="background:#0f766e"></span>معتمدة ${m.approved}</div><div><span class="legend-dot" style="background:#f59e0b"></span>بانتظار ${m.pending}</div><div><span class="legend-dot" style="background:#dc2626"></span>مخاطر ${counts.rejected}</div><div><span class="legend-dot" style="background:#38bdf8"></span>أخرى ${counts.other}</div>`;
renderPerformers(arr); renderLoadIndex(arr); renderBottlenecks(arr); renderWeekdayHeatmap(arr); renderSmartInsights(arr,m);}
function renderPerformers(arr){let by={}; arr.forEach(t=>{let k=t.assignee_name||'غير محدد'; by[k]=by[k]||{total:0,approved:0,late:0,weight:0}; by[k].total++; if(t.status==='approved')by[k].approved++; if(isOverdue(t))by[k].late++; by[k].weight+=taskWeight(t)}); let rows=Object.entries(by).map(([name,o])=>({name,score:Math.max(0,Math.round((o.approved/Math.max(1,o.total))*100 - o.late*8 + Math.min(10,o.weight))),...o})).sort((a,b)=>b.score-a.score).slice(0,5); document.getElementById('topPerformers').innerHTML=rows.length?rows.map((r,i)=>`<div class="performer"><div class="flex items-center gap-3"><div class="rank-badge">${i+1}</div><div><div class="font-black text-sm text-slate-800">${esc(r.name)}</div><div class="text-[11px] font-bold text-slate-500">${r.approved}/${r.total} معتمدة</div></div></div><div class="text-xl font-black text-teal-700">${r.score}%</div></div>`).join(''):'<div class="text-center text-slate-400 font-black p-8">لا توجد بيانات أداء بعد.</div>'}
function loadClass(v){return v>=13?'critical':(v>=8?'high':(v>=4?'medium':'low'))}function loadLabel(c){return {low:'منخفض',medium:'متوسط',high:'مرتفع',critical:'حرج'}[c]}
function renderLoadIndex(arr){let by={}; arr.filter(t=>!['approved','archived','withdrawn','rejected','canceled'].includes(t.status)).forEach(t=>{let k=t.assignee_name||'غير محدد'; by[k]=by[k]||{load:0,count:0}; by[k].load+=taskWeight(t)+(isOverdue(t)?2:0); by[k].count++}); let rows=Object.entries(by).map(([name,o])=>({name,...o,cls:loadClass(o.load)})).sort((a,b)=>b.load-a.load).slice(0,6); document.getElementById('loadIndex').innerHTML=rows.length?rows.map(r=>`<div class="performer"><div><div class="font-black text-sm text-slate-800">${esc(r.name)}</div><div class="text-[11px] font-bold text-slate-500">${r.count} تكليف نشط • حمل ${Math.round(r.load)}</div></div><span class="load-pill load-${r.cls}">${loadLabel(r.cls)}</span></div>`).join(''):'<div class="text-center text-slate-400 font-black p-8">لا يوجد حمل تشغيلي نشط.</div>'}
function renderBottlenecks(arr){let map=groupWeighted(arr.filter(t=>isOverdue(t)||['returned','rejected'].includes(t.status)),t=>t.record_key||t.title); renderBars('bottlenecks',map,{limit:5})}
function renderWeekdayHeatmap(arr){let days=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس']; let vals=[0,0,0,0,0]; arr.forEach(t=>{let d=parseDateSafe(t.due_date||t.created_at); if(!d)return; let day=d.getDay(); let idx=day===0?0:day===1?1:day===2?2:day===3?3:day===4?4:-1; if(idx>=0) vals[idx]++}); let max=Math.max(1,...vals); document.getElementById('weekdayHeatmap').innerHTML=days.map((d,i)=>{let lvl=vals[i]===0?0:Math.min(4,Math.ceil(vals[i]/max*4)); return `<div><div class="heat-cell heat-${lvl}">${vals[i]}</div><div class="text-center text-[11px] font-black text-slate-500 mt-2">${d}</div></div>`}).join('')}
function renderSmartInsights(arr,m){let insights=[]; if(m.overdue>0) insights.push(['🚨','توجد '+m.overdue+' تكليفات متأخرة تحتاج متابعة مباشرة من صاحب الصلاحية.']); if(m.pending>0) insights.push(['⏳','هناك '+m.pending+' تكليفات بانتظار الاعتماد؛ تأخر الاعتماد قد يبطئ دورة العمل.']); let roleMap=groupWeighted(arr.filter(t=>!['archived','canceled'].includes(t.status)),t=>roleLabel(t.assignee_role||'user')); let topRole=Object.entries(roleMap).sort((a,b)=>b[1]-a[1])[0]; if(topRole) insights.push(['📌','أعلى ضغط تشغيلي حاليًا يقع على فئة: '+topRole[0]+'.']); let lateByPerson=Object.entries(groupCount(arr.filter(isOverdue),t=>t.assignee_name)).sort((a,b)=>b[1]-a[1])[0]; if(lateByPerson) insights.push(['👤','أكثر منفذ يحتاج دعمًا في التأخير: '+lateByPerson[0]+' بعدد '+lateByPerson[1]+' تكليف.']); if(m.weighted>=85) insights.push(['🌟','مؤشر الإنجاز الموزون ممتاز، ويمكن توثيق هذه النتائج كشاهد أداء تشغيلي.']); if(!insights.length) insights.push(['✅','الوضع التشغيلي مستقر ولا توجد مؤشرات خطر حالية.']); document.getElementById('smartInsights').innerHTML=insights.slice(0,5).map(x=>`<div class="insight"><div class="ico">${x[0]}</div><div class="text-sm font-bold text-slate-700 leading-7">${esc(x[1])}</div></div>`).join('')}
function initAssigneeMode(){document.getElementById('pageHeading').textContent='مركز تكليفاتي';document.getElementById('pageSubtitle').textContent='تنفيذ التكليفات المرسلة إليك، رفع الشواهد، وإرسال الأعمال للاعتماد.';document.getElementById('ownerTabs').classList.add('hidden');document.getElementById('createView').classList.add('hidden');document.getElementById('listView').classList.remove('hidden');window.currentView='all';renderAll();renderList()}
function renderAll(){renderSummary(); if((window.currentView||'create')==='analytics') renderAnalytics(); else if((window.currentView||'create')!=='create') renderList()}
document.addEventListener('DOMContentLoaded',()=>{populateRecords();populateUsers();resetForm();document.getElementById('sourceOwner').addEventListener('change',populateRecords);document.getElementById('taskForm').addEventListener('submit',createTask);if(mode()==='assignee')initAssigneeMode();else renderAll()});
