const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');let pass=0,fail=0;
function check(name,cond){if(cond){console.log('PASS',name);pass++}else{console.error('FAIL',name);fail++}}
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const js=read('cloud-document-workspace.js'),repo=read('section-records-repository.js'),hub=read('cloud-upload-hub.js'),pf=read('supabase/functions/platform-files/index.ts'),be=read('supabase/functions/platform-document-workspace/index.ts'),sql=read('supabase/migrations/20260910134000_cloud_document_workspace_complete.sql'),center=read('cloud_files_center.html');
check('editable extensions DOCX/XLSX/PPTX',/docx.*xlsx.*pptx/.test(js));
check('reference mode blocks edit',js.includes("modeOf(file)!=='reference'"));
check('three document use modes',js.includes("['reference','work','continuous']"));
check('version restore action client',js.includes("restore-version"));
check('version preview UI',js.includes('data-preview'));
check('immutable evidence link helper',js.includes('immutableVersion:true'));
check('section library uses central workspace',repo.includes('editSectionRepoWorkspaceSafe'));
check('section library has version history',repo.includes('showSectionRepoVersionsSafe'));
check('section library asks use mode',repo.includes('sectionRepoUseMode'));
check('modern Office preview does not use HTML editor',repo.includes('للحفاظ على تنسيق Office الأصلي'));
check('upload hub asks use mode',hub.includes('cuhDocumentUseMode'));
check('upload hub lists current work files',hub.includes('data-work-files'));
check('upload hub edit action',hub.includes('data-work-edit'));
check('upload hub versions action',hub.includes('data-work-versions'));
check('center has edit action',center.includes('data-edit'));
check('center has version action',center.includes('data-vers'));
check('server derives school from platform session',be.includes("eq('school_id',s.school_id)"));
check('no school_id accepted from request for file lookup',!be.includes('body.school_id')&&!be.includes('body.schoolId'));
check('ownership edit check enforced',be.includes('canManage(s,f)'));
check('single writer lock',sql.includes('document_workspace_one_writer_idx'));
check('active+saving lock',sql.includes("status in ('active','saving')"));
check('heartbeat lock renewal',be.includes("action==='heartbeat'"));
check('ONLYOFFICE JWT verification',be.includes('jwtVerify'));
check('callback origin SSRF guard',be.includes('parsed.origin!==docOrigin'));
check('save creates new platform_files row',be.includes("from('platform_files').insert(payload)"));
check('old version archived not deleted',be.includes("update({status:'archived'"));
check('restore creates a new version',be.includes("workspaceProvider:'version_restore'"));
check('library links move to current version',be.includes('moveLibraryLinks'));
check('evidence links are not moved',be.includes("const isLibrary=String(l.relation_type||'')==='library_file'"));
check('archived versions remain previewable',pf.includes("['active','archived'].includes"));
check('deleted/trashed still blocked by signed-url state check',pf.includes("if(!['active','archived'].includes"));
check('no destructive migration drops platform file tables',!sql.match(/drop\s+table\s+.*platform_files/i));
check('RLS enabled for edit sessions',sql.includes('enable row level security'));
check('browser direct table access revoked',sql.includes('revoke all on table public.document_workspace_sessions'));
console.log(`RESULT ${pass} passed, ${fail} failed`);process.exit(fail?1:0);
